// LICENSE_CODE ZON ISC
'use strict'; /*jslint node:true, browser:true*/
(function(){
var define;
var is_node_ff = typeof module=='object' && module.exports;
if (!is_node_ff)
    define = self.define;
else
    define = require('./require_node.js').define(module, '../');
define([], function(){
var E = {};

E.list = {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AX: 'Aland Islands',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua And Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    JE: 'Bailiwick of Jersey',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BQ: 'Bonaire (Caribbean Netherlands)',
    BA: 'Bosnia And Herzegovina',
    BW: 'Botswana',
    BR: 'Brazil',
    BN: 'Brunei',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    CV: 'Cape Verde',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CI: "Cote D'Ivoire (Ivory Coast)",
    HR: 'Croatia (Hrvatska)',
    CU: 'Cuba',
    CW: 'Curacao',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    CD: 'Democratic Republic Of Congo (Zaire)',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EU: 'European Union',
    EE: 'Estonia',
    ET: 'Ethiopia',
    FK: 'Falkland Islands (Malvinas)',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GB: 'Great Britain',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GU: 'Guam',
    GP: 'Guadeloupe',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guinea',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HT: 'Haiti',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IO: 'British Indian Ocean Territory',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    XK: 'Kosovo',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Laos',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macau',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar (Burma)',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    AN: 'Netherlands Antilles',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    KP: 'North Korea',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestine',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn',
    PL: 'Poland',
    PM: 'Saint Pierre and Miquelon',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RU: 'Russia',
    RW: 'Rwanda',
    BL: 'Saint Barthelemy',
    SH: 'Saint Helena',
    KN: 'Saint Kitts And Nevis',
    LC: 'Saint Lucia',
    MF: 'Saint Martin',
    VC: 'Saint Vincent And The Grenadines',
    SM: 'San Marino',
    ST: 'Sao Tome And Principe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten (Dutch part)',
    SK: 'Slovak Republic',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia And South Sandwich Islands',
    KR: 'South Korea',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard and Jan Mayen',
    SZ: 'Swaziland',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad And Tobago',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks And Caicos Islands',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    UK: 'United Kingdom',
    US: 'United States',
    UM: 'United States Minor Outlying Islands',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VA: 'Vatican City (Holy See)',
    VE: 'Venezuela',
    VN: 'Vietnam',
    VG: 'Virgin Islands (British)',
    VI: 'Virgin Islands (US)',
    WF: 'Wallis And Futuna Islands',
    EH: 'Western Sahara',
    WS: 'Western Samoa',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
};

E.country_codes_lowered = Object.keys(E.list).map(function(c){
    return c.toLowerCase(); });

E.cn_list = {
    AF: '阿富汗',
    AL: '阿爾巴尼亞',
    DZ: '阿尔及利亚',
    AX: '奧蘭群島',
    AS: '美屬薩摩亞',
    AD: '安道爾',
    AO: '安哥拉',
    AI: '安圭拉島',
    AQ: '南極洲',
    AG: '安提瓜和巴布達',
    AR: '阿根廷',
    AM: '亚美尼亚',
    AW: '阿魯巴島',
    AU: '澳大利亚',
    AT: '奥地利',
    AZ: '阿塞拜疆',
    BS: '巴哈马',
    BH: '巴林',
    JE: '泽西岛',
    BD: '孟加拉國',
    BB: '巴巴多斯',
    BY: '白俄羅斯',
    BE: '比利時',
    BZ: '伯利茲',
    BJ: '贝宁',
    BM: '百慕大',
    BT: '不丹',
    BO: '玻利維亞',
    BQ: '博奈爾島（加勒比荷蘭）',
    BA: '波斯尼亚和黑塞哥维那',
    BW: '博茨瓦納',
    BR: '巴西',
    BN: '文萊',
    BG: '保加利亚',
    BF: '布基纳法索',
    BI: '布隆迪',
    KH: '柬埔寨',
    CM: '喀麦隆',
    CA: '加拿大',
    CV: '佛得角',
    KY: '开曼群岛',
    CF: '中非共和國',
    TD: '乍得',
    CL: '智利',
    CN: '中国',
    CX: '聖誕島',
    CC: '科科斯（基林）群島',
    CO: '哥倫比亞',
    KM: '科摩罗',
    CG: '刚果（布）',
    CK: '庫克群島',
    CR: '哥斯达黎加',
    CI: '科特迪瓦',
    HR: '克羅地亞（Hrvatska）',
    CU: '古巴',
    CW: '库拉索',
    CY: '塞浦路斯',
    CZ: '捷克',
    CD: '剛果民主共和國（扎伊爾）',
    DK: '丹麦',
    DJ: '吉布提',
    DM: '多米尼加',
    DO: '多明尼加共和國',
    EC: '厄瓜多尔',
    EG: '埃及',
    SV: '萨尔瓦多',
    GQ: '赤道幾內亞',
    ER: '厄立特里亞',
    EU: '歐洲聯盟',
    EE: '愛沙尼亞',
    ET: '埃塞俄比亞',
    FK: '福克蘭群島（馬爾維納斯）',
    FO: '法羅群島',
    FJ: '斐濟',
    FI: '芬兰',
    FR: '法国',
    GF: '法屬圭亞那',
    PF: '法属波利尼西亚',
    TF: '法屬南部領地',
    GA: '加蓬',
    GM: '冈比亚',
    GE: '佐治亞州',
    DE: '德国',
    GH: '加納',
    GI: '直布罗陀',
    GB: '大不列顛',
    GR: '希腊',
    GL: '格陵蘭',
    GD: '格林納達',
    GU: '关岛',
    GP: '瓜德罗普',
    GT: '危地马拉',
    GG: '根西島',
    GN: '几内亚',
    GW: '幾內亞比紹',
    GY: '圭亞那',
    HT: '海地',
    HN: '洪都拉斯',
    HK: '香港',
    HU: '匈牙利',
    IS: '冰岛',
    IN: '印度',
    ID: '印度尼西亞',
    IR: '伊朗',
    IQ: '伊拉克',
    IE: '愛爾蘭',
    IM: '马恩岛',
    IL: '以色列',
    IT: '意大利',
    JM: '牙買加',
    JP: '日本',
    JO: '約旦',
    KZ: '哈薩克斯坦',
    KE: '肯尼亞',
    KI: '基里巴斯',
    XK: '科索沃',
    KW: '科威特',
    KG: '吉尔吉斯斯坦',
    LA: '老撾',
    LV: '拉脫維亞',
    LB: '黎巴嫩',
    LS: '莱索托',
    LR: '利比里亚',
    LY: '利比亚',
    LI: '列支敦士登',
    LT: '立陶宛',
    LU: '盧森堡',
    MO: '澳門',
    MK: '马其顿',
    MG: '马达加斯加',
    MW: '马拉维',
    MY: '马来西亚',
    MV: '马尔代夫',
    ML: '马里',
    MT: '馬耳他',
    MH: '馬紹爾群島',
    MQ: '馬提尼克島',
    MR: '毛里塔尼亚',
    MU: '毛里求斯',
    YT: '馬約特島',
    MX: '墨西哥',
    FM: '密克羅尼西亞',
    MD: '摩爾多瓦',
    MC: '摩納哥',
    MN: '蒙古',
    ME: '黑山',
    MS: '蒙特塞拉特',
    MA: '摩洛哥',
    MZ: '莫桑比克',
    MM: '緬甸',
    NA: '纳米比亚',
    NR: '瑙鲁',
    NP: '尼泊爾',
    NL: '荷兰',
    AN: '荷屬安的列斯',
    NC: '新喀里多尼亚',
    NZ: '新西兰',
    NI: '尼加拉瓜',
    NE: '尼日爾',
    NG: '尼日利亚',
    NU: '纽埃',
    NF: '诺福克岛',
    KP: '北朝鮮',
    MP: '北馬里亞納群島',
    NO: '挪威',
    OM: '阿曼',
    PK: '巴基斯坦',
    PW: 'u琉',
    PS: '巴勒斯坦',
    PA: '巴拿馬',
    PG: '巴布亞新幾內亞',
    PY: '巴拉圭',
    PE: '秘魯',
    PH: '菲律宾',
    PN: '皮特凱恩',
    PL: '波兰',
    PT: '葡萄牙',
    PR: '波多黎各',
    QA: '卡塔尔',
    RE: '團圓',
    RO: '罗马尼亚',
    RU: '俄罗斯',
    RW: '卢旺达',
    BL: '聖巴托洛繆島',
    SH: '聖海倫娜',
    KN: '聖基茨和尼維斯',
    LC: '聖盧西亞',
    MF: '聖馬丁',
    VC: '聖文森特和格林納丁斯',
    SM: '圣马力诺',
    ST: '聖多美和普林西比',
    SA: '沙特阿拉伯',
    SN: '塞内加尔',
    RS: '塞爾維亞',
    SC: '塞舌爾',
    SL: '塞拉利昂',
    SG: '新加坡',
    SX: '荷属圣马丁',
    SK: '斯洛伐克共和國',
    SI: '斯洛文尼亚',
    SB: '所羅門群島',
    SO: '索马里',
    ZA: '南非',
    GS: '南喬治亞島和南桑威奇群島',
    KR: '朝鲜',
    SS: '南蘇丹',
    ES: '西班牙',
    LK: '斯里蘭卡',
    SD: '苏丹',
    SR: '蘇里南',
    SZ: '斯威士兰',
    SE: '瑞典',
    CH: '瑞士',
    SY: '叙利亚',
    TW: '台湾省',
    TJ: '塔吉克斯坦',
    TZ: '坦桑尼亚',
    TH: '泰国',
    TL: '東帝汶',
    TG: '多哥',
    TK: '托克劳群岛',
    TO: '湯加',
    TT: '特立尼达和多巴哥',
    TN: '突尼斯',
    TR: '土耳其',
    TM: '土庫曼斯坦',
    TC: '特克斯和凱科斯群島',
    TV: '圖瓦盧',
    UG: '烏干達',
    UA: '乌克兰',
    AE: '阿拉伯聯合酋長國',
    UK: '英国',
    US: '美国',
    UY: '乌拉圭',
    UZ: '烏茲別克斯坦',
    VU: '瓦努阿圖',
    VA: '梵蒂岡（羅馬教廷）',
    VE: '委內瑞拉',
    VN: '越南',
    VG: '維爾京群島（英國）',
    VI: '維爾京群島（美國）',
    WF: '瓦利斯和富图纳群岛',
    EH: '西撒哈拉',
    WS: '薩摩亞西部',
    YE: '也门',
    ZM: '赞比亚',
    ZW: '津巴布韦',
};
// https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/
// master/all/all.json
// rm keys that are not in E.list
var alpha_3_list = {
    AD: 'AND',
    AE: 'ARE',
    AF: 'AFG',
    AG: 'ATG',
    AI: 'AIA',
    AL: 'ALB',
    AM: 'ARM',
    AO: 'AGO',
    AQ: 'ATA',
    AR: 'ARG',
    AS: 'ASM',
    AT: 'AUT',
    AU: 'AUS',
    AW: 'ABW',
    AX: 'ALA',
    AZ: 'AZE',
    BA: 'BIH',
    BB: 'BRB',
    BD: 'BGD',
    BE: 'BEL',
    BF: 'BFA',
    BG: 'BGR',
    BH: 'BHR',
    BI: 'BDI',
    BJ: 'BEN',
    BL: 'BLM',
    BM: 'BMU',
    BN: 'BRN',
    BO: 'BOL',
    BQ: 'BES',
    BR: 'BRA',
    BS: 'BHS',
    BT: 'BTN',
    BW: 'BWA',
    BY: 'BLR',
    BZ: 'BLZ',
    CA: 'CAN',
    CC: 'CCK',
    CD: 'COD',
    CF: 'CAF',
    CG: 'COG',
    CH: 'CHE',
    CI: 'CIV',
    CK: 'COK',
    CL: 'CHL',
    CM: 'CMR',
    CN: 'CHN',
    CO: 'COL',
    CR: 'CRI',
    CU: 'CUB',
    CV: 'CPV',
    CW: 'CUW',
    CX: 'CXR',
    CY: 'CYP',
    CZ: 'CZE',
    DE: 'DEU',
    DJ: 'DJI',
    DK: 'DNK',
    DM: 'DMA',
    DO: 'DOM',
    DZ: 'DZA',
    EC: 'ECU',
    EE: 'EST',
    EG: 'EGY',
    EH: 'ESH',
    ER: 'ERI',
    ES: 'ESP',
    ET: 'ETH',
    FI: 'FIN',
    FJ: 'FJI',
    FK: 'FLK',
    FM: 'FSM',
    FO: 'FRO',
    FR: 'FRA',
    GA: 'GAB',
    GB: 'GBR',
    GD: 'GRD',
    GE: 'GEO',
    GF: 'GUF',
    GG: 'GGY',
    GH: 'GHA',
    GI: 'GIB',
    GL: 'GRL',
    GM: 'GMB',
    GN: 'GIN',
    GP: 'GLP',
    GQ: 'GNQ',
    GR: 'GRC',
    GS: 'SGS',
    GT: 'GTM',
    GU: 'GUM',
    GW: 'GNB',
    GY: 'GUY',
    HK: 'HKG',
    HN: 'HND',
    HR: 'HRV',
    HT: 'HTI',
    HU: 'HUN',
    ID: 'IDN',
    IO: 'IOT',
    IE: 'IRL',
    IL: 'ISR',
    IM: 'IMN',
    IN: 'IND',
    IQ: 'IRQ',
    IR: 'IRN',
    IS: 'ISL',
    IT: 'ITA',
    JE: 'JEY',
    JM: 'JAM',
    JO: 'JOR',
    JP: 'JPN',
    KE: 'KEN',
    KG: 'KGZ',
    KH: 'KHM',
    KI: 'KIR',
    KM: 'COM',
    KN: 'KNA',
    KP: 'PRK',
    KR: 'KOR',
    KW: 'KWT',
    KY: 'CYM',
    KZ: 'KAZ',
    LA: 'LAO',
    LB: 'LBN',
    LC: 'LCA',
    LI: 'LIE',
    LK: 'LKA',
    LR: 'LBR',
    LS: 'LSO',
    LT: 'LTU',
    LU: 'LUX',
    LV: 'LVA',
    LY: 'LBY',
    MA: 'MAR',
    MC: 'MCO',
    MD: 'MDA',
    ME: 'MNE',
    MF: 'MAF',
    MG: 'MDG',
    MH: 'MHL',
    MK: 'MKD',
    ML: 'MLI',
    MM: 'MMR',
    MN: 'MNG',
    MO: 'MAC',
    MP: 'MNP',
    MQ: 'MTQ',
    MR: 'MRT',
    MS: 'MSR',
    MT: 'MLT',
    MU: 'MUS',
    MV: 'MDV',
    MW: 'MWI',
    MX: 'MEX',
    MY: 'MYS',
    MZ: 'MOZ',
    NA: 'NAM',
    NC: 'NCL',
    NE: 'NER',
    NF: 'NFK',
    NG: 'NGA',
    NI: 'NIC',
    NL: 'NLD',
    NO: 'NOR',
    NP: 'NPL',
    NR: 'NRU',
    NU: 'NIU',
    NZ: 'NZL',
    OM: 'OMN',
    PA: 'PAN',
    PE: 'PER',
    PF: 'PYF',
    PG: 'PNG',
    PH: 'PHL',
    PK: 'PAK',
    PL: 'POL',
    PN: 'PCN',
    PM: 'SPM',
    PR: 'PRI',
    PS: 'PSE',
    PT: 'PRT',
    PW: 'PLW',
    PY: 'PRY',
    QA: 'QAT',
    RE: 'REU',
    RO: 'ROU',
    RS: 'SRB',
    RU: 'RUS',
    RW: 'RWA',
    SA: 'SAU',
    SB: 'SLB',
    SC: 'SYC',
    SD: 'SDN',
    SE: 'SWE',
    SG: 'SGP',
    SH: 'SHN',
    SI: 'SVN',
    SK: 'SVK',
    SL: 'SLE',
    SM: 'SMR',
    SN: 'SEN',
    SO: 'SOM',
    SR: 'SUR',
    SS: 'SSD',
    ST: 'STP',
    SV: 'SLV',
    SX: 'SXM',
    SY: 'SYR',
    SZ: 'SWZ',
    TC: 'TCA',
    TD: 'TCD',
    TF: 'ATF',
    TG: 'TGO',
    TH: 'THA',
    TJ: 'TJK',
    TK: 'TKL',
    TL: 'TLS',
    TM: 'TKM',
    TN: 'TUN',
    TO: 'TON',
    TR: 'TUR',
    TT: 'TTO',
    TV: 'TUV',
    TW: 'TWN',
    TZ: 'TZA',
    UA: 'UKR',
    UG: 'UGA',
    US: 'USA',
    UY: 'URY',
    UZ: 'UZB',
    VA: 'VAT',
    VC: 'VCT',
    VE: 'VEN',
    VG: 'VGB',
    VI: 'VIR',
    VN: 'VNM',
    VU: 'VUT',
    WF: 'WLF',
    WS: 'WSM',
    YE: 'YEM',
    YT: 'MYT',
    ZA: 'ZAF',
    ZM: 'ZMB',
    ZW: 'ZWE',
};

// XXX saarya: merge with list
E.adj_list = {
    AF: {name: 'Afghanistan', adj: 'Afghan'},
    AX: {name: 'Åland Islands', adj: 'Åland Island'},
    AL: {name: 'Albania', adj: 'Albanian'},
    DZ: {name: 'Algeria', adj: 'Algerian'},
    AS: {name: 'American Samoa', adj: 'American Samoan'},
    AD: {name: 'Andorra', adj: 'Andorran'},
    AO: {name: 'Angola', adj: 'Angolan'},
    AI: {name: 'Anguilla', adj: 'Anguillan'},
    AG: {name: 'Antigua and Barbuda', adj: 'Antiguan'},
    AR: {name: 'Argentina', adj: 'Argentinian'},
    AM: {name: 'Armenia', adj: 'Armenian'},
    AW: {name: 'Aruba', adj: 'Aruban'},
    AU: {name: 'Australia', adj: 'Australian'},
    AT: {name: 'Austria', adj: 'Austrian'},
    AZ: {name: 'Azerbaijan', adj: 'Azerbaijani'},
    BS: {name: 'Bahamas', adj: 'Bahamian'},
    BH: {name: 'Bahrain', adj: 'Bahraini'},
    BD: {name: 'Bangladesh', adj: 'Bengali'},
    BB: {name: 'Barbados', adj: 'Barbadian'},
    BY: {name: 'Belarus', adj: 'Belarusian'},
    BE: {name: 'Belgium', adj: 'Belgian'},
    BZ: {name: 'Belize', adj: 'Belizean'},
    BJ: {name: 'Benin', adj: 'Beninese'},
    BM: {name: 'Bermuda', adj: 'Bermudan'},
    BT: {name: 'Bhutan', adj: 'Bhutanese'},
    BO: {name: 'Bolivia', adj: 'Bolivian'},
    BA: {name: 'Bosnia and Herzegovina', adj: 'Bosnian'},
    BW: {name: 'Botswana', adj: 'Botswanan'},
    BR: {name: 'Brazil', adj: 'Brazilian'},
    BN: {name: 'Brunei', adj: 'Bruneian'},
    BG: {name: 'Bulgaria', adj: 'Bulgarian'},
    BF: {name: 'Burkina Faso', adj: 'Burkinabé'},
    BI: {name: 'Burundi', adj: 'Burundian'},
    CV: {name: 'Cabo Verde', adj: 'Cabo Verdean'},
    KH: {name: 'Cambodia', adj: 'Cambodian'},
    CM: {name: 'Cameroon', adj: 'Cameroonian'},
    CA: {name: 'Canada', adj: 'Canadian'},
    KY: {name: 'Cayman Islands', adj: 'Caymanian'},
    TD: {name: 'Chad', adj: 'Chadian'},
    CL: {name: 'Chile', adj: 'Chilean'},
    CN: {name: 'China', adj: 'Chinese'},
    CX: {name: 'Christmas Island', adj: 'Christmas Island'},
    CO: {name: 'Colombia', adj: 'Colombian'},
    KM: {name: 'Comoros', adj: 'Comoran'},
    CG: {name: 'Congo', adj: 'Congolese'},
    CK: {name: 'Cook Islands', adj: 'Cook Island'},
    CR: {name: 'Costa Rica', adj: 'Costa Rican'},
    CI: {name: 'Côte d\'Ivoire', adj: 'Ivorian'},
    HR: {name: 'Croatia', adj: 'Croatian'},
    CU: {name: 'Cuba', adj: 'Cuban'},
    CW: {name: 'Curaçao', adj: 'Curaçaoan'},
    CY: {name: 'Cyprus', adj: 'Cypriot'},
    CZ: {name: 'Czech Republic', adj: 'Czech'},
    DK: {name: 'Denmark', adj: 'Danish'},
    DJ: {name: 'Djibouti', adj: 'Djiboutian'},
    DM: {name: 'Dominica', adj: 'Dominican'},
    DO: {name: 'Dominican Republic', adj: 'Dominican'},
    EC: {name: 'Ecuador', adj: 'Ecuadorian'},
    EG: {name: 'Egypt', adj: 'Egyptian'},
    SV: {name: 'El Salvador', adj: 'Salvadoran'},
    GQ: {name: 'Equatorial Guinea', adj: 'Equatorial Guinean'},
    EE: {name: 'Estonia', adj: 'Estonian'},
    ET: {name: 'Ethiopia', adj: 'Ethiopian'},
    FO: {name: 'Faroe Islands', adj: 'Faroese'},
    FJ: {name: 'Fiji', adj: 'Fijian'},
    FI: {name: 'Finland', adj: 'Finnish'},
    FR: {name: 'France', adj: 'French'},
    PF: {name: 'French Polynesia', adj: 'French Polynesian'},
    GA: {name: 'Gabon', adj: 'Gabonese'},
    GM: {name: 'Gambia', adj: 'Gambian'},
    GE: {name: 'Georgia', adj: 'Georgian'},
    DE: {name: 'Germany', adj: 'German'},
    GH: {name: 'Ghana', adj: 'Ghanaian'},
    GI: {name: 'Gibraltar', adj: 'Gibraltar'},
    GR: {name: 'Greece', adj: 'Greek'},
    GL: {name: 'Greenland', adj: 'Greenlandic'},
    GD: {name: 'Grenada', adj: 'Grenadian'},
    GU: {name: 'Guam', adj: 'Guamanian'},
    GT: {name: 'Guatemala', adj: 'Guatemalan'},
    GG: {name: 'Guernsey', adj: 'Channel Island'},
    GN: {name: 'Guinea', adj: 'Guinean'},
    GW: {name: 'Guinea-Bissau', adj: 'Bissau-Guinean'},
    GY: {name: 'Guyana', adj: 'Guyanese'},
    HT: {name: 'Haiti', adj: 'Haitian'},
    HN: {name: 'Honduras', adj: 'Honduran'},
    HK: {name: 'Hong Kong', adj: 'Hong Kong'},
    HU: {name: 'Hungary', adj: 'Hungarian'},
    IS: {name: 'Iceland', adj: 'Icelandic'},
    IN: {name: 'India', adj: 'Indian'},
    ID: {name: 'Indonesia', adj: 'Indonesian'},
    IO: {name: 'British Indian Ocean Territory', adj: 'Indian'},
    IR: {name: 'Iran', adj: 'Iranian'},
    IQ: {name: 'Iraq', adj: 'Iraqi'},
    IE: {name: 'Ireland', adj: 'Irish'},
    IM: {name: 'Isle of Man', adj: 'Manx'},
    IL: {name: 'Israel', adj: 'Israeli'},
    IT: {name: 'Italy', adj: 'Italian'},
    JM: {name: 'Jamaica', adj: 'Jamaican'},
    JP: {name: 'Japan', adj: 'Japanese'},
    JE: {name: 'Jersey', adj: 'Channel Island'},
    JO: {name: 'Jordan', adj: 'Jordanian'},
    KZ: {name: 'Kazakhstan', adj: 'Kazakhstani'},
    KE: {name: 'Kenya', adj: 'Kenyan'},
    KI: {name: 'Kiribati', adj: 'I-Kiribati'},
    KW: {name: 'Kuwait', adj: 'Kuwaiti'},
    KG: {name: 'Kyrgyzstan', adj: 'Kyrgyzstani'},
    LA: {name: 'Laos', adj: 'Lao, Laotian'},
    LV: {name: 'Latvia', adj: 'Latvian'},
    LB: {name: 'Lebanon', adj: 'Lebanese'},
    LS: {name: 'Lesotho', adj: 'Basotho'},
    LR: {name: 'Liberia', adj: 'Liberian'},
    LY: {name: 'Libya', adj: 'Libyan'},
    LI: {name: 'Liechtenstein', adj: 'Liechtensteiner'},
    LT: {name: 'Lithuania', adj: 'Lithuanian'},
    LU: {name: 'Luxembourg', adj: 'Luxembourgish'},
    MO: {name: 'Macau', adj: 'Macanese'},
    MK: {name: 'Macedonia', adj: 'Macedonian'},
    MG: {name: 'Madagascar', adj: 'Malagasy'},
    MW: {name: 'Malawi', adj: 'Malawian'},
    MY: {name: 'Malaysia', adj: 'Malaysian'},
    MV: {name: 'Maldives', adj: 'Maldivian'},
    ML: {name: 'Mali', adj: 'Malian'},
    MT: {name: 'Malta', adj: 'Maltese'},
    MH: {name: 'Marshall Islands', adj: 'Marshallese'},
    MQ: {name: 'Martinique', adj: 'Martinican'},
    MR: {name: 'Mauritania', adj: 'Mauritanian'},
    MU: {name: 'Mauritius', adj: 'Mauritian'},
    YT: {name: 'Mayotte', adj: 'Mahoran'},
    MX: {name: 'Mexico', adj: 'Mexican'},
    FM: {name: 'Micronesia', adj: 'Micronesian'},
    MD: {name: 'Moldova', adj: 'Moldovan'},
    MC: {name: 'Monaco', adj: 'Monacan'},
    MN: {name: 'Mongolia', adj: 'Mongolian'},
    ME: {name: 'Montenegro', adj: 'Montenegrin'},
    MA: {name: 'Morocco', adj: 'Moroccan'},
    MZ: {name: 'Mozambique', adj: 'Mozambican'},
    MM: {name: 'Myanmar', adj: 'Burmese'},
    NA: {name: 'Namibia', adj: 'Namibian'},
    NR: {name: 'Nauru', adj: 'Nauruan'},
    NP: {name: 'Nepal', adj: 'Nepali'},
    NL: {name: 'Netherlands', adj: 'Dutch'},
    NC: {name: 'New Caledonia', adj: 'New Caledonian'},
    NZ: {name: 'New Zealand', adj: 'Zelanian'},
    NI: {name: 'Nicaragua', adj: 'Nicaraguan'},
    NE: {name: 'Niger', adj: 'Nigerien'},
    NG: {name: 'Nigeria', adj: 'Nigerian'},
    MP: {name: 'Northern Mariana Islands', adj: 'Niuean'},
    NO: {name: 'Norway', adj: 'Norwegian'},
    OM: {name: 'Oman', adj: 'Omani'},
    PK: {name: 'Pakistan', adj: 'Pakistani'},
    PW: {name: 'Palau', adj: 'Palauan'},
    PS: {name: 'Palestine', adj: 'Palestinian'},
    PA: {name: 'Panama', adj: 'Panamanian'},
    PG: {name: 'Papua New Guinea', adj: 'Papuan'},
    PY: {name: 'Paraguay', adj: 'Paraguayan'},
    PE: {name: 'Peru', adj: 'Peruvian'},
    PH: {name: 'Philippines', adj: 'Filipino'},
    PL: {name: 'Poland', adj: 'Polish'},
    PT: {name: 'Portugal', adj: 'Portuguese'},
    PR: {name: 'Puerto Rico', adj: 'Puerto Rican'},
    QA: {name: 'Qatar', adj: 'Qatari'},
    RO: {name: 'Romania', adj: 'Romanian'},
    RU: {name: 'Russia', adj: 'Russian'},
    RW: {name: 'Rwanda', adj: 'Rwandan'},
    BL: {name: 'Saint Barthélemy', adj: 'Barthélemois'},
    KN: {name: 'Saint Kitts and Nevis', adj: 'Kittitian'},
    LC: {name: 'Saint Lucia', adj: 'Saint Lucian'},
    MF: {name: 'Saint Martin', adj: 'Saint-Martinoise'},
    VC: {name: 'Saint Vincent and the Grenadines', adj: 'Saint Vincentian'},
    SM: {name: 'San Marino', adj: 'Sammarinese'},
    SA: {name: 'Saudi Arabia', adj: 'Saudi'},
    SN: {name: 'Senegal', adj: 'Senegalese'},
    RS: {name: 'Serbia', adj: 'Serbian'},
    SC: {name: 'Seychelles', adj: 'Seychellois'},
    SL: {name: 'Sierra Leone', adj: 'Sierra Leonean'},
    SG: {name: 'Singapore', adj: 'Singaporean'},
    SK: {name: 'Slovakia', adj: 'Slovak'},
    SI: {name: 'Slovenia', adj: 'Slovenian'},
    SB: {name: 'Solomon Islands', adj: 'Solomon Island'},
    SO: {name: 'Somalia', adj: 'Somali'},
    ZA: {name: 'South Africa', adj: 'South African'},
    KR: {name: 'South Korea', adj: 'South Korean'},
    SS: {name: 'South Sudan', adj: 'South Sudanese'},
    ES: {name: 'Spain', adj: 'Spanish'},
    LK: {name: 'Sri Lanka', adj: 'Sri Lankan'},
    SD: {name: 'Sudan', adj: 'Sudanese'},
    SR: {name: 'Surinam', adj: 'Surinamese'},
    SZ: {name: 'Swaziland', adj: 'Swazi'},
    SE: {name: 'Sweden', adj: 'Swedish'},
    CH: {name: 'Switzerland', adj: 'Swiss'},
    SY: {name: 'Syria', adj: 'Syrian'},
    TW: {name: 'Taiwan', adj: 'Taiwanese'},
    TJ: {name: 'Tajikistan', adj: 'Tajikistani'},
    TZ: {name: 'Tanzania', adj: 'Tanzanian'},
    TH: {name: 'Thailand', adj: 'Thai'},
    TL: {name: 'Timor-Leste', adj: 'Timorese'},
    TG: {name: 'Togo', adj: 'Togolese'},
    TT: {name: 'Trinidad and Tobago', adj: 'Trinidadian'},
    TN: {name: 'Tunisia', adj: 'Tunisian'},
    TR: {name: 'Turkey', adj: 'Turkish'},
    TC: {name: 'Turks and Caicos Islands', adj: 'Turks and Caicos Island'},
    UG: {name: 'Uganda', adj: 'Ugandan'},
    UA: {name: 'Ukraine', adj: 'Ukrainian'},
    AE: {name: 'United Arab Emirates', adj: 'Emirati'},
    GB: {name: 'United Kingdom', adj: 'British'},
    US: {name: 'United States', adj: 'American'},
    UY: {name: 'Uruguay', adj: 'Uruguayan'},
    UZ: {name: 'Uzbekistan', adj: 'Uzbekistani'},
    VU: {name: 'Vanuatu', adj: 'Vanuatuan'},
    VE: {name: 'Venezuela', adj: 'Venezuelan'},
    VN: {name: 'Vietnam', adj: 'Vietnamese'},
    VG: {name: 'Virgin Islands, British', adj: 'British Virgin Island'},
    VI: {name: 'Virgin Islands, United States', adj: 'U.S. Virgin Island'},
    YE: {name: 'Yemen', adj: 'Yemeni'},
    ZM: {name: 'Zambia', adj: 'Zambian'},
    ZW: {name: 'Zimbabwe', adj: 'Zimbabwean'},
};

E.timezone = {
    CI: 'Africa/Abidjan',
    GH: 'Africa/Accra',
    ET: 'Africa/Addis_Ababa',
    DZ: 'Africa/Algiers',
    ER: 'Africa/Asmara',
    ML: 'Africa/Bamako',
    CF: 'Africa/Bangui',
    GM: 'Africa/Banjul',
    GW: 'Africa/Bissau',
    MW: 'Africa/Blantyre',
    CG: 'Africa/Brazzaville',
    BI: 'Africa/Bujumbura',
    EG: 'Africa/Cairo',
    MA: 'Africa/Casablanca',
    GN: 'Africa/Conakry',
    SN: 'Africa/Dakar',
    TZ: 'Africa/Dar_es_Salaam',
    DJ: 'Africa/Djibouti',
    CM: 'Africa/Douala',
    EH: 'Africa/El_Aaiun',
    SL: 'Africa/Freetown',
    BW: 'Africa/Gaborone',
    ZW: 'Africa/Harare',
    ZA: 'Africa/Johannesburg',
    SS: 'Africa/Juba',
    UG: 'Africa/Kampala',
    SD: 'Africa/Khartoum',
    RW: 'Africa/Kigali',
    CD: 'Africa/Kinshasa',
    NG: 'Africa/Lagos',
    GA: 'Africa/Libreville',
    TG: 'Africa/Lome',
    AO: 'Africa/Luanda',
    ZM: 'Africa/Lusaka',
    GQ: 'Africa/Malabo',
    MZ: 'Africa/Maputo',
    LS: 'Africa/Maseru',
    SZ: 'Africa/Mbabane',
    SO: 'Africa/Mogadishu',
    LR: 'Africa/Monrovia',
    KE: 'Africa/Nairobi',
    TD: 'Africa/Ndjamena',
    NE: 'Africa/Niamey',
    MR: 'Africa/Nouakchott',
    BF: 'Africa/Ouagadougou',
    BJ: 'Africa/Porto-Novo',
    ST: 'Africa/Sao_Tome',
    LY: 'Africa/Tripoli',
    TN: 'Africa/Tunis',
    NA: 'Africa/Windhoek',
    AI: 'America/Anguilla',
    AG: 'America/Antigua',
    AR: 'America/Argentina/Buenos_Aires',
    AW: 'America/Aruba',
    PY: 'America/Asuncion',
    BB: 'America/Barbados',
    BZ: 'America/Belize',
    CO: 'America/Bogota',
    VE: 'America/Caracas',
    KY: 'America/Cayman',
    CR: 'America/Costa_Rica',
    CW: 'America/Curacao',
    DM: 'America/Dominica',
    SV: 'America/El_Salvador',
    GL: 'America/Godthab',
    TC: 'America/Grand_Turk',
    GD: 'America/Grenada',
    GT: 'America/Guatemala',
    EC: 'America/Guayaquil',
    GY: 'America/Guyana',
    CU: 'America/Havana',
    JM: 'America/Jamaica',
    BO: 'America/La_Paz',
    PE: 'America/Lima',
    NI: 'America/Managua',
    MF: 'America/Marigot',
    MQ: 'America/Martinique',
    MX: 'America/Mexico_City',
    UY: 'America/Montevideo',
    MS: 'America/Montserrat',
    PM: 'America/Miquelon',
    BS: 'America/Nassau',
    BR: 'America/Sao_Paulo',
    PA: 'America/Panama',
    SR: 'America/Paramaribo',
    HT: 'America/Port-au-Prince',
    TT: 'America/Port_of_Spain',
    PR: 'America/Puerto_Rico',
    CL: 'America/Santiago',
    DO: 'America/Santo_Domingo',
    BL: 'America/St_Barthelemy',
    KN: 'America/St_Kitts',
    LC: 'America/St_Lucia',
    VI: 'America/St_Thomas',
    VC: 'America/St_Vincent',
    HN: 'America/Tegucigalpa',
    VG: 'America/Tortola',
    AQ: 'Pacific/Auckland',
    YE: 'Asia/Aden',
    KZ: 'Asia/Almaty',
    JO: 'Asia/Amman',
    TM: 'Asia/Ashgabat',
    IQ: 'Asia/Baghdad',
    BH: 'Asia/Bahrain',
    AZ: 'Asia/Baku',
    TH: 'Asia/Bangkok',
    LB: 'Asia/Beirut',
    KG: 'Asia/Bishkek',
    BN: 'Asia/Brunei',
    IN: 'Asia/Colombo',
    LK: 'Asia/Colombo',
    SY: 'Asia/Damascus',
    BD: 'Asia/Dhaka',
    TL: 'Asia/Dili',
    AE: 'Asia/Dubai',
    TJ: 'Asia/Dushanbe',
    PS: 'Asia/Gaza',
    VN: 'Asia/Ho_Chi_Minh',
    HK: 'Asia/Hong_Kong',
    ID: 'Asia/Jakarta',
    AF: 'Asia/Kabul',
    PK: 'Asia/Karachi',
    NP: 'Asia/Kathmandu',
    MY: 'Asia/Kuala_Lumpur',
    KW: 'Asia/Kuwait',
    MO: 'Asia/Macau',
    PH: 'Asia/Manila',
    OM: 'Asia/Muscat',
    CY: 'Asia/Nicosia',
    KH: 'Asia/Phnom_Penh',
    KP: 'Asia/Pyongyang',
    QA: 'Asia/Qatar',
    MM: 'Asia/Rangoon',
    SA: 'Asia/Riyadh',
    KR: 'Asia/Seoul',
    CN: 'Asia/Shanghai',
    SG: 'Asia/Singapore',
    TW: 'Asia/Taipei',
    UZ: 'Asia/Tashkent',
    GE: 'Asia/Tbilisi',
    IR: 'Asia/Tehran',
    BT: 'Asia/Thimphu',
    JP: 'Asia/Tokyo',
    MN: 'Asia/Ulaanbaatar',
    LA: 'Asia/Vientiane',
    AM: 'Asia/Yerevan',
    BM: 'Atlantic/Bermuda',
    CV: 'Atlantic/Cape_Verde',
    FO: 'Atlantic/Faroe',
    IS: 'Atlantic/Reykjavik',
    GS: 'Atlantic/South_Georgia',
    SH: 'Atlantic/St_Helena',
    FK: 'Atlantic/Stanley',
    AU: 'Australia/Sydney',
    CA: 'America/Toronto',
    NL: 'Europe/Amsterdam',
    AD: 'Europe/Andorra',
    GR: 'Europe/Athens',
    RS: 'Europe/Belgrade',
    DE: 'Europe/Berlin',
    SK: 'Europe/Bratislava',
    BE: 'Europe/Brussels',
    RO: 'Europe/Bucharest',
    HU: 'Europe/Budapest',
    DK: 'Europe/Copenhagen',
    IE: 'Europe/Dublin',
    GI: 'Europe/Gibraltar',
    GG: 'Europe/Guernsey',
    FI: 'Europe/Helsinki',
    IM: 'Europe/Isle_of_Man',
    MD: 'Europe/Istanbul',
    TR: 'Europe/Istanbul',
    JE: 'Europe/Jersey',
    UA: 'Europe/Kiev',
    PT: 'Europe/Lisbon',
    SI: 'Europe/Ljubljana',
    GB: 'Europe/London',
    UK: 'Europe/London',
    LU: 'Europe/Luxembourg',
    ES: 'Europe/Madrid',
    MT: 'Europe/Malta',
    AX: 'Europe/Mariehamn',
    BY: 'Europe/Minsk',
    MC: 'Europe/Monaco',
    RU: 'Europe/Moscow',
    NO: 'Europe/Oslo',
    FR: 'Europe/Paris',
    ME: 'Europe/Podgorica',
    CZ: 'Europe/Prague',
    LV: 'Europe/Riga',
    IT: 'Europe/Rome',
    SM: 'Europe/San_Marino',
    BA: 'Europe/Sarajevo',
    MK: 'Europe/Skopje',
    BG: 'Europe/Sofia',
    SE: 'Europe/Stockholm',
    EE: 'Europe/Tallinn',
    AL: 'Europe/Tirane',
    LI: 'Europe/Vaduz',
    VA: 'Europe/Vatican',
    AT: 'Europe/Vienna',
    LT: 'Europe/Vilnius',
    HR: 'Europe/Zagreb',
    CH: 'Europe/Zurich',
    MG: 'Indian/Antananarivo',
    CX: 'Indian/Christmas',
    CC: 'Indian/Cocos',
    KM: 'Indian/Comoro',
    TF: 'Indian/Kerguelen',
    SC: 'Indian/Mahe',
    MV: 'Indian/Maldives',
    MU: 'Indian/Mauritius',
    YT: 'Indian/Mayotte',
    IO: 'Indian/Chagos',
    IL: 'Israel',
    WS: 'Pacific/Apia',
    NZ: 'Pacific/Auckland',
    FM: 'Pacific/Chuuk',
    VU: 'Pacific/Efate',
    TK: 'Pacific/Fakaofo',
    FJ: 'Pacific/Fiji',
    TV: 'Pacific/Funafuti',
    SB: 'Pacific/Guadalcanal',
    GU: 'Pacific/Guam',
    MH: 'Pacific/Majuro',
    NR: 'Pacific/Nauru',
    NU: 'Pacific/Niue',
    NF: 'Pacific/Norfolk',
    NC: 'Pacific/Noumea',
    AS: 'Pacific/Pago_Pago',
    PW: 'Pacific/Palau',
    PN: 'Pacific/Pitcairn',
    PG: 'Pacific/Port_Moresby',
    CK: 'Pacific/Rarotonga',
    MP: 'Pacific/Saipan',
    PF: 'Pacific/Tahiti',
    KI: 'Pacific/Tarawa',
    TO: 'Pacific/Tongatapu',
    WF: 'Pacific/Wallis',
    PL: 'Europe/Warsaw',
    US: 'America/New_York',
    GF: 'America/Cayenne',
};
E.regions = {
    AD: ['Southern Europe', 'EMEA'],
    AE: ['Western Asia', 'EMEA'],
    AF: ['Southern Asia', 'APAC'],
    AG: ['Caribbean', 'AMER'],
    AI: ['Caribbean', 'AMER'],
    AL: ['South-Eastern Europe', 'EMEA'],
    AM: ['Western Asia', 'EMEA'],
    AN: ['Caribbean'],
    AO: ['Middle Africa', 'EMEA'],
    AQ: ['Antarctica', 'APAC'],
    AR: ['South America', 'AMER'],
    AS: ['Polynesia', 'South America', 'AMER'],
    AT: ['Western Europe', 'EMEA', 'EU'],
    AU: ['Australia and New Zealand', 'APAC'],
    AW: ['Caribbean', 'AMER'],
    AX: ['Scandinavia', 'EMEA', 'Northern Europe'],
    AZ: ['Western Asia', 'EMEA'],
    BA: ['South-Eastern Europe', 'EMEA'],
    BB: ['Caribbean', 'AMER'],
    BD: ['Southern Asia', 'APAC'],
    BE: ['Western Europe', 'EMEA', 'EU'],
    BF: ['Western Africa', 'EMEA'],
    BG: ['Eastern Europe', 'EMEA', 'EU'],
    BH: ['Western Asia', 'EMEA'],
    BI: ['Eastern Africa', 'EMEA'],
    BJ: ['Western Africa', 'EMEA'],
    BL: ['Caribbean', 'AMER'],
    BM: ['Northern America', 'AMER'],
    BN: ['South-Eastern Asia', 'APAC'],
    BO: ['South America', 'AMER'],
    BQ: ['Caribbean', 'AMER'],
    BR: ['South America', 'AMER'],
    BS: ['Caribbean', 'AMER'],
    BT: ['Southern Asia', 'APAC'],
    BW: ['Southern Africa', 'EMEA'],
    BY: ['Eastern Europe', 'EMEA'],
    BZ: ['South America', 'AMER'],
    CA: ['Northern America', 'AMER'],
    CC: ['Australia and New Zealand', 'APAC'],
    CD: ['Middle Africa', 'EMEA'],
    CF: ['Middle Africa', 'EMEA'],
    CG: ['Middle Africa', 'EMEA'],
    CH: ['Western Europe', 'EMEA'],
    CI: ['Western Africa', 'EMEA'],
    CK: ['Polynesia', 'APAC'],
    CL: ['South America', 'AMER'],
    CM: ['Middle Africa', 'EMEA'],
    CN: ['Asia', 'China', 'APAC'],
    CO: ['South America', 'AMER'],
    CR: ['South America', 'AMER'],
    CU: ['Caribbean', 'AMER'],
    CV: ['Western Africa', 'EMEA'],
    CW: ['Caribbean', 'AMER'],
    CX: ['Australia and New Zealand', 'APAC'],
    CY: ['South-Eastern Europe', 'EMEA', 'EU'],
    CZ: ['Eastern Europe', 'EMEA', 'EU'],
    DE: ['Western Europe', 'EMEA', 'EU'],
    DJ: ['Eastern Africa', 'EMEA'],
    DK: ['Scandinavia', 'EMEA', 'Northern Europe', 'EU'],
    DM: ['Caribbean', 'AMER'],
    DO: ['Caribbean', 'AMER'],
    DZ: ['Northern Africa', 'EMEA'],
    EC: ['South America', 'AMER'],
    EE: ['Eastern Europe', 'EMEA', 'EU'],
    EG: ['Northern Africa', 'EMEA'],
    EH: ['Northern Africa', 'EMEA'],
    ER: ['Eastern Africa', 'EMEA'],
    ES: ['Southern Europe', 'EMEA', 'EU'],
    ET: ['Eastern Africa', 'EMEA'],
    EU: ['Western Europe'],
    FI: ['Scandinavia', 'EMEA', 'Northern Europe', 'EU'],
    FJ: ['Melanesia', 'APAC'],
    FK: ['South America', 'AMER'],
    FM: ['Micronesia', 'APAC'],
    FO: ['Scandinavia', 'EMEA', 'Northern Europe'],
    FR: ['Western Europe', 'EMEA', 'EU'],
    GA: ['Middle Africa', 'EMEA'],
    GB: ['Northern Europe', 'EMEA'],
    GD: ['Caribbean', 'AMER'],
    GE: ['Western Asia', 'EMEA'],
    GF: ['South America', 'AMER'],
    GG: ['Northern Europe', 'EMEA'],
    GH: ['Western Africa', 'EMEA'],
    GI: ['Southern Europe', 'EMEA'],
    GL: ['Scandinavia', 'EMEA', 'Northern Europe'],
    GM: ['Western Africa', 'EMEA'],
    GN: ['Western Africa', 'EMEA'],
    GP: ['Caribbean', 'AMER'],
    GQ: ['Middle Africa', 'EMEA'],
    GR: ['South-Eastern Europe', 'EMEA', 'EU'],
    GS: ['Antarctica', 'South America', 'AMER'],
    GT: ['South America', 'AMER'],
    GU: ['Micronesia', 'APAC'],
    GW: ['Western Africa', 'EMEA'],
    GY: ['South America', 'AMER'],
    HK: ['Eastern Asia', 'APAC'],
    HN: ['South America', 'AMER'],
    HR: ['South-Eastern Europe', 'EMEA', 'EU'],
    HT: ['Caribbean', 'AMER'],
    HU: ['Eastern Europe', 'EMEA', 'EU'],
    ID: ['South-Eastern Asia', 'APAC'],
    IO: ['Eastern Africa', 'AMER'],
    IE: ['Northern Europe', 'EMEA', 'EU'],
    IL: ['Western Asia', 'EMEA'],
    IM: ['Northern Europe', 'EMEA'],
    IN: ['Southern Asia', 'APAC'],
    IQ: ['Western Asia', 'EMEA'],
    IR: ['Southern Asia', 'EMEA'],
    IS: ['Scandinavia', 'EMEA', 'Northern Europe'],
    IT: ['Southern Europe', 'EMEA', 'EU'],
    JE: ['Northern Europe', 'EMEA'],
    JM: ['Caribbean', 'AMER'],
    JO: ['Western Asia', 'EMEA'],
    JP: ['Eastern Asia', 'APAC'],
    KE: ['Eastern Africa', 'EMEA'],
    KG: ['Central Asia', 'EMEA'],
    KH: ['South-Eastern Asia', 'APAC'],
    KI: ['Micronesia', 'APAC'],
    KM: ['Eastern Africa', 'EMEA'],
    KN: ['Caribbean', 'AMER'],
    KP: ['Eastern Asia', 'APAC'],
    KR: ['Eastern Asia', 'APAC'],
    KW: ['Western Asia', 'EMEA'],
    KY: ['Caribbean', 'AMER'],
    KZ: ['Central Asia', 'EMEA'],
    LA: ['South-Eastern Asia', 'APAC'],
    LB: ['Western Asia', 'EMEA'],
    LC: ['Caribbean', 'AMER'],
    LI: ['Western Europe', 'EMEA'],
    LK: ['Southern Asia', 'APAC'],
    LR: ['Western Africa', 'EMEA'],
    LS: ['Southern Africa', 'EMEA'],
    LT: ['Eastern Europe', 'EMEA', 'EU'],
    LU: ['Western Europe', 'EMEA', 'EU'],
    LV: ['Eastern Europe', 'EMEA', 'EU'],
    LY: ['Northern Africa', 'EMEA'],
    MA: ['Northern Africa', 'EMEA'],
    MC: ['Western Europe', 'EMEA'],
    MD: ['Eastern Europe', 'EMEA'],
    ME: ['South-Eastern Europe', 'EMEA'],
    MF: ['Caribbean', 'AMER'],
    MG: ['Eastern Africa', 'EMEA'],
    MH: ['Micronesia', 'APAC'],
    MK: ['South-Eastern Europe', 'EMEA'],
    ML: ['Western Africa', 'EMEA'],
    MM: ['South-Eastern Asia', 'APAC'],
    MN: ['Eastern Asia', 'APAC'],
    MO: ['Eastern Asia', 'EMEA'],
    MP: ['Micronesia', 'APAC'],
    MQ: ['Caribbean', 'AMER'],
    MR: ['Western Africa', 'EMEA'],
    MS: ['Caribbean', 'AMER'],
    MT: ['Southern Europe', 'EMEA', 'EU'],
    MU: ['Eastern Africa', 'EMEA'],
    MV: ['Southern Asia', 'APAC'],
    MW: ['Eastern Africa', 'EMEA'],
    MX: ['South America', 'AMER'],
    MY: ['South-Eastern Asia', 'APAC'],
    MZ: ['Eastern Africa', 'EMEA'],
    NA: ['Southern Africa', 'EMEA'],
    NC: ['Melanesia', 'APAC'],
    NE: ['Western Africa', 'EMEA'],
    NF: ['Australia and New Zealand', 'APAC'],
    NG: ['Western Africa', 'EMEA'],
    NI: ['South America', 'AMER'],
    NL: ['Western Europe', 'EMEA', 'EU'],
    NO: ['Scandinavia', 'EMEA', 'Northern Europe'],
    NP: ['Southern Asia', 'APAC'],
    NR: ['Micronesia', 'APAC'],
    NU: ['Polynesia', 'APAC'],
    NZ: ['Australia and New Zealand', 'APAC'],
    OM: ['Western Asia', 'EMEA'],
    PA: ['South America', 'AMER'],
    PE: ['South America', 'AMER'],
    PF: ['Polynesia', 'APAC'],
    PG: ['Melanesia', 'APAC'],
    PH: ['South-Eastern Asia', 'APAC'],
    PK: ['Southern Asia', 'APAC'],
    PL: ['Eastern Europe', 'EMEA', 'EU'],
    PN: ['Polynesia', 'AMER', 'South America'],
    PM: ['Northern America', 'AMER'],
    PR: ['Caribbean', 'AMER'],
    PS: ['Western Asia', 'EMEA'],
    PT: ['Southern Europe', 'EMEA', 'EU'],
    PW: ['Micronesia', 'APAC'],
    PY: ['South America', 'AMER'],
    QA: ['Western Asia', 'EMEA'],
    RE: ['Eastern Africa', 'APAC'],
    RO: ['Eastern Europe', 'EMEA', 'EU'],
    RS: ['South-Eastern Europe', 'EMEA'],
    RU: ['Eastern Europe', 'EMEA'],
    RW: ['Eastern Africa', 'EMEA'],
    SA: ['Western Asia', 'EMEA'],
    SB: ['Melanesia', 'APAC'],
    SC: ['Eastern Africa', 'EMEA'],
    SD: ['Northern Africa', 'EMEA'],
    SE: ['Scandinavia', 'EMEA', 'Northern Europe', 'EU'],
    SG: ['South-Eastern Asia', 'APAC'],
    SH: ['Western Africa', 'EMEA'],
    SI: ['South-Eastern Europe', 'EMEA'],
    SJ: ['Sourh America', 'AMER'],
    SK: ['Eastern Europe', 'EMEA', 'EU'],
    SL: ['Western Africa', 'EMEA', 'EU'],
    SM: ['Southern Europe', 'EMEA'],
    SN: ['Western Africa', 'EMEA'],
    SO: ['Eastern Africa', 'EMEA'],
    SR: ['South America', 'AMER'],
    SS: ['Eastern Africa', 'EMEA'],
    ST: ['Middle Africa', 'EMEA'],
    SV: ['South America', 'AMER'],
    SX: ['Caribbean', 'AMER'],
    SY: ['Western Asia', 'EMEA'],
    SZ: ['Southern Africa', 'EMEA'],
    TC: ['Caribbean', 'AMER'],
    TD: ['Middle Africa', 'EMEA'],
    TF: ['Antarctica', 'EMEA'],
    TG: ['Western Africa', 'EMEA'],
    TH: ['South-Eastern Asia', 'APAC'],
    TJ: ['Central Asia', 'APAC'],
    TK: ['Polynesia', 'APAC'],
    TL: ['South-Eastern Asia', 'APAC'],
    TM: ['Central Asia', 'APAC'],
    TN: ['Northern Africa', 'EMEA'],
    TO: ['Polynesia', 'APAC'],
    TR: ['South-Eastern Europe', 'EMEA'],
    TT: ['Caribbean', 'AMER'],
    TV: ['Polynesia', 'APAC'],
    TW: ['Eastern Asia', 'APAC'],
    TZ: ['Eastern Africa', 'EMEA'],
    UA: ['Eastern Europe', 'EMEA'],
    UG: ['Eastern Africa', 'EMEA'],
    UK: ['Northern Europe', 'EMEA'],
    UM: ['APAC'],
    US: ['Northern America', 'AMER'],
    UY: ['South America', 'AMER'],
    UZ: ['Central Asia', 'EMEA'],
    VA: ['Southern Europe', 'EMEA'],
    VC: ['Caribbean', 'AMER'],
    VE: ['South America', 'AMER'],
    VG: ['Caribbean', 'AMER'],
    VI: ['Caribbean', 'AMER'],
    VN: ['South-Eastern Asia', 'APAC'],
    VU: ['Melanesia', 'APAC'],
    WF: ['Polynesia', 'APAC'],
    WS: ['Polynesia', 'APAC'],
    XK: ['South-Eastern Europe', 'EMEA'],
    YE: ['Western Asia', 'EMEA'],
    YT: ['Eastern Africa', 'EMEA'],
    ZA: ['Southern Africa', 'EMEA'],
    ZM: ['Eastern Africa', 'EMEA'],
    ZW: ['Eastern Africa', 'EMEA'],
};
E.region = {};
for (var cn in E.regions)
{
    var codes = ['EMEA', 'AMER', 'APAC'];
    var regions = E.regions[cn];
    var code = codes.find(function(c){ return regions.includes(c); });
    if (code)
        E.region[cn] = code;
    else if (regions.includes('China'))
        E.region[cn] = 'APAC';
}

var supraregions = {
    'Northern America': ['America'],
    'South America': ['LATAM'],
    'Central America': ['LATAM'],
    Caribbean: ['LATAM', 'South America'],
    LATAM: ['America'],
    'Eastern Europe': ['Eastern Europe (W/E)'],
    'South-Eastern Europe': ['Eastern Europe (W/E)'],
    'Western Europe': ['Western Europe (W/E)'],
    'Southern Europe': ['Western Europe (W/E)'],
    'Northern Europe': ['Western Europe (W/E)'],
    'Western Europe (W/E)': ['Europe'],
    'Eastern Europe (W/E)': ['Europe'],
    Polynesia: ['Oceania'],
    Melanesia: ['Oceania'],
    Micronesia: ['Oceania'],
    'Australia and New Zealand': ['Oceania'],
    Oceania: ['APAC'],
    'South-Eastern Asia': ['APAC', 'Asia'],
    'Southern Asia': ['APAC', 'Asia'],
    'Eastern Asia': ['APAC', 'Asia'],
    'Central Asia': ['Asia'],
    'Western Asia': ['Asia'],
    'Eastern Africa': ['Africa'],
    'Western Africa': ['Africa'],
    'Southern Africa': ['Africa'],
    'Northern Africa': ['Africa'],
    'Middle Africa': ['Africa'],
    'EU': ['Europe']
};
E.country_terr = {};
var terr_country = {
    apac_r: ['AF', 'AQ', 'AU', 'BT', 'BN', 'KH', 'CX', 'CC', 'CK', 'FJ',
    'PF', 'GU', 'ID', 'JP', 'KI', 'KP', 'KR', 'LA', 'MY', 'MH', 'FM', 'MN',
    'MM', 'NR', 'NP', 'NC', 'NZ', 'NU', 'NF', 'MP', 'PK', 'PW', 'PG', 'PH',
    'WS', 'SG', 'SB', 'TW', 'TJ', 'TH', 'TL', 'TK', 'TO', 'TM', 'TV', 'UM',
    'VU', 'VN', 'WF'],
    emea_e: ['AL', 'DZ', 'AO', 'AM', 'AZ', 'BH', 'BY', 'BJ', 'BA', 'BW', 'BG',
    'BF', 'BI', 'CV', 'CM', 'CF', 'TD', 'KM', 'CG', 'CD', 'CI', 'HR', 'CY',
    'CZ', 'DJ', 'EG', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'TF', 'GA', 'GM', 'GE',
    'GH', 'GR', 'GN', 'GW', 'HU', 'IR', 'IQ', 'IL', 'JO', 'KZ', 'KE', 'KW',
    'KG', 'LV', 'LB', 'LS', 'LR', 'LY', 'LT', 'MO', 'MG', 'MW', 'ML', 'MR',
    'MU', 'YT', 'MD', 'ME', 'MA', 'MZ', 'NA', 'NE', 'NG', 'MK', 'OM',
    'PS', 'PL', 'QA', 'RO', 'RU', 'RW', 'SH', 'ST', 'SA', 'SN', 'RS', 'SC',
    'SL', 'SK', 'SI', 'SO', 'ZA', 'SS', 'SD', 'SY', 'TZ', 'TG', 'TN', 'TR',
    'UG', 'UA', 'AE', 'UZ', 'EH', 'YE', 'ZM', 'ZW', 'XK'],
    emea_w: ['AX', 'AD', 'AT', 'BE', 'DK', 'FO', 'FI', 'FR', 'DE', 'GI', 'GL',
    'GG', 'VA', 'IS', 'IE', 'IM', 'IT', 'JE', 'LI', 'LU', 'MT', 'MC', 'NO',
    'PT', 'SM', 'ES', 'SE', 'CH', 'UK', 'GB', 'NL'],
    in: ['IN', 'BD', 'LK', 'RE', 'MV'],
    amer_e: ['CA'],
    amer_w: ['US'],
    amer_s: ['AS', 'AI', 'AG', 'AR', 'AW', 'BS', 'BB', 'BZ', 'BM', 'BO', 'BQ',
    'BV', 'BR', 'IO', 'KY', 'CL', 'CO', 'CR', 'CU', 'CW', 'DM', 'DO', 'EC',
    'SV', 'FK', 'GF', 'GD', 'GP', 'GT', 'GY', 'HT', 'HM', 'HN', 'JM', 'MQ',
    'MX', 'MS', 'NI', 'PA', 'PY', 'PE', 'PN', 'PR', 'BL', 'KN', 'LC', 'MF',
    'PM', 'VC', 'SX', 'GS', 'SR', 'SJ', 'TT', 'TC', 'UY', 'VE', 'VG', 'VI'],
    cn: ['CN', 'HK'],
};
Object.entries(terr_country).forEach(function(ct){
    ct[1].forEach(function(c){ E.country_terr[c] = ct[0]; });
});

E.old_country_terr = {};
var old_terr_country = {
    apac_rest: 'VN SG JP MY KR AU TH ID NP PH AE PK NZ TW SA KW BN AF CX KH '
    +'IR MM IQ YE OM LA MN PF BH KP NU NC BT VU WS FJ AQ CK CC KI PW TJ TM '
    +'MP GU MH PG UM AU TL SB FM NR NF TK TO TV WF',
    east_med_africa: 'IL TR CY ZA GR EG MU JO NG MG KE ET CM MO GH CH CI ZW '
    +'SN BJ PS TZ NA SZ QA MW TG NE BF LR TD GN UG AO CV BW ML ZM SY SO SH SC '
    +'MZ LS GM CG ER EH DJ CD RW SS KM GA GQ SL MR CF LY LB GW TF YT ST SD',
    east_europe: 'RU RO CZ ME UA PL LT SI BY BG RS KZ AM EE LV GE MD HR HU SK '
    +'MK AL AZ KG BA UZ BI XK SM',
    in: 'IN BD LK RE MV',
    uk_ie_dach: 'DE AT CH UK GB IE IM',
    west_europe: 'FR ES NL IT PT BE AD MT MC MA LU TN DZ GI LI SE DK FI NO AX '
    +'IS GG JE EU GL VA FX FO',
};
Object.entries(old_terr_country).forEach(function(ct){
    ct[1].split(' ').forEach(function(c){ E.old_country_terr[c] = ct[0]; });
});

E.state_terr = {
    US: {
        AK: 'amer_w',
        AL: 'amer_e',
        AR: 'amer_w',
        AZ: 'amer_w',
        CA: 'amer_w',
        CO: 'amer_w',
        CT: 'amer_e',
        DC: 'amer_e',
        DE: 'amer_e',
        FL: 'amer_e',
        GA: 'amer_e',
        HI: 'amer_w',
        IA: 'amer_w',
        ID: 'amer_w',
        IL: 'amer_e',
        IN: 'amer_e',
        KS: 'amer_w',
        KY: 'amer_e',
        LA: 'amer_w',
        MA: 'amer_e',
        MD: 'amer_e',
        ME: 'amer_e',
        MI: 'amer_e',
        MN: 'amer_w',
        MO: 'amer_w',
        MS: 'amer_e',
        MT: 'amer_w',
        NC: 'amer_e',
        ND: 'amer_w',
        NE: 'amer_w',
        NH: 'amer_e',
        NJ: 'amer_e',
        NM: 'amer_w',
        NV: 'amer_w',
        NY: 'amer_e',
        OH: 'amer_e',
        OK: 'amer_w',
        OR: 'amer_w',
        PA: 'amer_e',
        RI: 'amer_e',
        SC: 'amer_e',
        SD: 'amer_w',
        TN: 'amer_e',
        TX: 'amer_w',
        UT: 'amer_w',
        VA: 'amer_e',
        VT: 'amer_e',
        WA: 'amer_w',
        WI: 'amer_e',
        WV: 'amer_e',
        WY: 'amer_w',
    },
};

var extend_regions = function(_regions, country_code){
    for (var i = 0; i<_regions.length; i++)
    {
        (supraregions[_regions[i]]||[])
        .filter(function(extra){ return !_regions.includes(extra); })
        .forEach(function(extra){ _regions.push(extra); });
    }
    _regions.push('All');
};
for (var region_country in E.regions)
    extend_regions(E.regions[region_country], region_country);

E.is_country_code = function(c){
    return typeof c=='string'&&c.length==2
        &&E.country_codes_lowered.includes(c.toLowerCase());
};

E.non_iso = {GB: 1, EU: 1};

E.lum_easy_pass = {
    AR: 1,
    AT: 1,
    AU: 1,
    BE: 1,
    CA: 1,
    EU: 1,
    FL: 1,
    FR: 1,
    DE: 1,
    GB: 1,
    IE: 1,
    IL: 1,
    IT: 1,
    NL: 1,
    NZ: 1,
    PL: 1,
    PT: 1,
    SG: 1,
    KR: 1,
    CH: 1,
    SE: 1,
    UK: 1,
    US: 1,
    JP: 1,
};

E.dialing_code_list = {
    AF: '93',
    AL: '355',
    DZ: '213',
    AX: '358',
    AS: '1684',
    AD: '376',
    AO: '244',
    AI: '1264',
    AQ: '672',
    AG: '1268',
    AR: '54',
    AM: '374',
    AW: '297',
    AU: '61',
    AT: '43',
    AZ: '994',
    BS: '1242',
    BH: '973',
    JE: '44',
    BD: '880',
    BB: '1246',
    BY: '375',
    BE: '32',
    BZ: '501',
    BJ: '229',
    BM: '1441',
    BT: '975',
    BO: '591',
    BA: '387',
    BW: '267',
    BR: '55',
    BN: '673',
    BG: '359',
    BF: '226',
    BI: '257',
    KH: '855',
    CM: '237',
    CV: '238',
    KY: '1345',
    CF: '236',
    TD: '235',
    CL: '56',
    CN: '86',
    CX: '61',
    CC: '61',
    CO: '57',
    KM: '269',
    CG: '242',
    CK: '682',
    CR: '506',
    CI: '225',
    HR: '385',
    CU: '53',
    CW: '599',
    CY: '357',
    CZ: '420',
    CD: '243',
    DK: '45',
    DJ: '253',
    DM: '1767',
    EC: '593',
    EG: '20',
    SV: '503',
    GQ: '240',
    ER: '291',
    EE: '372',
    ET: '251',
    FK: '500',
    FO: '298',
    FJ: '679',
    FI: '358',
    FR: '33',
    PF: '689',
    TF: '262',
    GA: '241',
    GM: '220',
    GE: '995',
    DE: '49',
    GH: '233',
    GI: '350',
    GB: '44',
    GR: '30',
    GL: '299',
    GD: '1473',
    GU: '1671',
    GT: '502',
    GG: '44',
    GN: '224',
    GW: '245',
    GY: '592',
    HT: '509',
    HN: '504',
    HK: '852',
    HU: '36',
    IS: '354',
    IN: '91',
    ID: '62',
    IR: '98',
    IQ: '964',
    IE: '353',
    IM: '44',
    IO: '246',
    IL: '972',
    IT: '39',
    JM: '1876',
    JP: '81',
    JO: '962',
    KE: '254',
    KI: '686',
    KW: '965',
    KG: '996',
    LA: '856',
    LV: '371',
    LB: '961',
    LS: '266',
    LR: '231',
    LY: '218',
    LI: '423',
    LT: '370',
    LU: '352',
    MO: '853',
    MK: '389',
    MG: '261',
    MW: '265',
    MY: '60',
    MV: '960',
    ML: '223',
    MT: '356',
    MH: '692',
    MQ: '596',
    MR: '222',
    MU: '230',
    YT: '262',
    MX: '52',
    FM: '691',
    MD: '373',
    MC: '377',
    MN: '976',
    ME: '382',
    MS: '1664',
    MA: '212',
    MZ: '258',
    MM: '95',
    NA: '264',
    NR: '674',
    NP: '977',
    NL: '31',
    AN: '599',
    NC: '687',
    NZ: '64',
    NI: '505',
    NE: '227',
    NG: '234',
    NU: '683',
    NF: '672',
    KP: '850',
    MP: '1670',
    NO: '47',
    OM: '968',
    PK: '92',
    PW: '680',
    PS: '970',
    PA: '507',
    PG: '675',
    PY: '595',
    PE: '51',
    PH: '63',
    PN: '64',
    PM: '508',
    PL: '48',
    PT: '351',
    QA: '974',
    RO: '40',
    RW: '250',
    BL: '590',
    SH: '290',
    KN: '1869',
    LC: '1758',
    MF: '590',
    VC: '1784',
    SM: '378',
    ST: '239',
    SA: '966',
    SN: '221',
    RS: '381',
    SC: '248',
    SL: '232',
    SG: '65',
    SK: '421',
    SI: '386',
    SB: '677',
    SO: '252',
    ZA: '27',
    GS: '500',
    KR: '82',
    SS: '211',
    ES: '34',
    LK: '94',
    SD: '249',
    SR: '597',
    SZ: '268',
    SE: '46',
    CH: '41',
    SY: '963',
    TW: '886',
    TJ: '992',
    TZ: '255',
    TH: '66',
    TL: '670',
    TG: '228',
    TK: '690',
    TO: '676',
    TT: '1868',
    TN: '216',
    TR: '90',
    TM: '993',
    TC: '1649',
    TV: '688',
    UG: '256',
    UA: '380',
    AE: '971',
    UK: '44',
    UY: '598',
    UZ: '998',
    VU: '678',
    VA: '39',
    VE: '58',
    VN: '84',
    VG: '1284',
    VI: '1340',
    WF: '681',
    EH: '212',
    WS: '685',
    YE: '967',
    ZM: '260',
    ZW: '263',
    DO: '1',
    CA: '1',
    KZ: '7',
    US: '1',
    PR: '1',
    RU: '7',
};

E.dialing_code_rlist = {
    1: 'US',
    1403: 'CA', 1587: 'CA', 1780: 'CA', 1825: 'CA', // Alberta
    1236: 'CA', 1250: 'CA', 1604: 'CA', 1778: 'CA', // British Columbia
    1204: 'CA', 1431: 'CA', // Manitoba
    1506: 'CA', // New Brunswick
    1709: 'CA', // Newfoundland and Labrador
    1902: 'CA', 1782: 'CA', // Nova Scotia and Prince Edward Island
    1226: 'CA', 1249: 'CA', 1289: 'CA', 1343: 'CA', 1365: 'CA', 1416: 'CA',
    1437: 'CA', 1519: 'CA', 1548: 'CA', 1613: 'CA', 1647: 'CA', 1705: 'CA',
    1807: 'CA', 1905: 'CA', // Ontario
    1418: 'CA', 1438: 'CA', 1450: 'CA', 1514: 'CA', 1579: 'CA', 1581: 'CA',
    1819: 'CA', 1873: 'CA', // Quebec
    1306: 'CA', 1639: 'CA', // Saskatchewan
    1867: 'CA', // Yukon, Northwest Territories and Nunavut
    1787: 'PR', 1939: 'PR',
    1809: 'DO', 1829: 'DO', 1849: 'DO',
    1242: 'BS',
    1246: 'BB',
    1264: 'AI',
    1268: 'AG',
    1284: 'VG',
    1340: 'VI',
    1345: 'KY',
    1441: 'BM',
    1473: 'GD',
    1649: 'TC',
    1664: 'MS',
    1670: 'MP',
    1671: 'GU',
    1684: 'AS',
    1758: 'LC',
    1767: 'DM',
    1784: 'VC',
    1868: 'TT',
    1869: 'KN',
    1876: 'JM',
    20: 'EG',
    211: 'SS',
    212: 'MA',
    212528: 'EH',
    213: 'DZ',
    216: 'TN',
    218: 'LY',
    220: 'GM',
    221: 'SN',
    222: 'MR',
    223: 'ML',
    224: 'GN',
    225: 'CI',
    226: 'BF',
    227: 'NE',
    228: 'TG',
    229: 'BJ',
    230: 'MU',
    231: 'LR',
    232: 'SL',
    233: 'GH',
    234: 'NG',
    235: 'TD',
    236: 'CF',
    237: 'CM',
    238: 'CV',
    239: 'ST',
    240: 'GQ',
    241: 'GA',
    242: 'CG',
    243: 'CD',
    244: 'AO',
    245: 'GW',
    246: 'IO',
    248: 'SC',
    249: 'SD',
    250: 'RW',
    251: 'ET',
    252: 'SO',
    253: 'DJ',
    254: 'KE',
    255: 'TZ',
    256: 'UG',
    257: 'BI',
    258: 'MZ',
    260: 'ZM',
    261: 'MG',
    262: 'TF',
    262269: 'YT', 262639: 'YT',
    263: 'ZW',
    264: 'NA',
    265: 'MW',
    266: 'LS',
    267: 'BW',
    268: 'SZ',
    269: 'KM',
    27: 'ZA',
    290: 'SH',
    291: 'ER',
    297: 'AW',
    298: 'FO',
    299: 'GL',
    30: 'GR',
    31: 'NL',
    32: 'BE',
    33: 'FR',
    34: 'ES',
    350: 'GI',
    351: 'PT',
    352: 'LU',
    353: 'IE',
    354: 'IS',
    355: 'AL',
    356: 'MT',
    357: 'CY',
    358: 'FI',
    35818: 'AX', 358457: 'AX',
    359: 'BG',
    36: 'HU',
    370: 'LT',
    371: 'LV',
    372: 'EE',
    373: 'MD',
    374: 'AM',
    375: 'BY',
    376: 'AD',
    377: 'MC',
    378: 'SM',
    380: 'UA',
    381: 'RS',
    382: 'ME',
    385: 'HR',
    386: 'SI',
    387: 'BA',
    389: 'MK',
    39: 'IT',
    39066987: 'VA',
    39066988: 'VA',
    40: 'RO',
    41: 'CH',
    420: 'CZ',
    421: 'SK',
    423: 'LI',
    43: 'AT',
    44: 'GB',
    441481: 'GG',
    441534: 'JE',
    441624: 'IM',
    45: 'DK',
    46: 'SE',
    47: 'NO',
    48: 'PL',
    49: 'DE',
    500: 'FK',
    501: 'BZ',
    502: 'GT',
    503: 'SV',
    504: 'HN',
    505: 'NI',
    506: 'CR',
    507: 'PA',
    508: 'PM',
    509: 'HT',
    51: 'PE',
    52: 'MX',
    53: 'CU',
    54: 'AR',
    55: 'BR',
    56: 'CL',
    57: 'CO',
    58: 'VE',
    590: 'BL',
    591: 'BO',
    592: 'GY',
    593: 'EC',
    595: 'PY',
    596: 'MQ',
    597: 'SR',
    598: 'UY',
    599: 'AN',
    60: 'MY',
    61: 'AU',
    619162: 'CC',
    619164: 'CX',
    62: 'ID',
    63: 'PH',
    64: 'NZ',
    65: 'SG',
    66: 'TH',
    670: 'TL',
    6721: 'AQ',
    67232: 'NF',
    67235: 'NF',
    673: 'BN',
    674: 'NR',
    675: 'PG',
    676: 'TO',
    677: 'SB',
    678: 'VU',
    679: 'FJ',
    680: 'PW',
    681: 'WF',
    682: 'CK',
    683: 'NU',
    685: 'WS',
    686: 'KI',
    687: 'NC',
    688: 'TV',
    689: 'PF',
    690: 'TK',
    691: 'FM',
    692: 'MH',
    7: 'RU',
    76: 'KZ', 77: 'KZ',
    81: 'JP',
    82: 'KR',
    84: 'VN',
    850: 'KP',
    852: 'HK',
    853: 'MO',
    855: 'KH',
    856: 'LA',
    86: 'CN',
    880: 'BD',
    886: 'TW',
    90: 'TR',
    91: 'IN',
    92: 'PK',
    93: 'AF',
    94: 'LK',
    95: 'MM',
    960: 'MV',
    961: 'LB',
    962: 'JO',
    963: 'SY',
    964: 'IQ',
    965: 'KW',
    966: 'SA',
    967: 'YE',
    968: 'OM',
    970: 'PS',
    971: 'AE',
    972: 'IL',
    973: 'BH',
    974: 'QA',
    975: 'BT',
    976: 'MN',
    977: 'NP',
    98: 'IR',
    992: 'TJ',
    993: 'TM',
    994: 'AZ',
    995: 'GE',
    996: 'KG',
    998: 'UZ',
};

// records with "Parent" column equal to "Country"/"Region" from this list:
// https://developers.google.com/adwords/api/docs/appendix/geotargeting
// intersected with "Region Setting" from https://www.google.com/preferences
// plus countries from https://support.google.com/google-ads/answer/6163740
E.google_list = {
    AD: 'Andorra',
    AE: 'United Arab Emirates',
    AF: 'Afghanistan',
    AG: 'Antigua and Barbuda',
    AI: 'Anguilla',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AQ: 'Antarctica',
    AR: 'Argentina',
    AS: 'American Samoa',
    AT: 'Austria',
    AU: 'Australia',
    AZ: 'Azerbaijan',
    BA: 'Bosnia and Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladesh',
    BE: 'Belgium',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BI: 'Burundi',
    BJ: 'Benin',
    BN: 'Brunei',
    BO: 'Bolivia',
    BQ: 'Caribbean Netherlands',
    BR: 'Brazil',
    BS: 'The Bahamas',
    BT: 'Bhutan',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Cocos (Keeling) Islands',
    CD: 'Democratic Republic of the Congo',
    CF: 'Central African Republic',
    CG: 'Republic of the Congo',
    CH: 'Switzerland',
    CI: 'Cote d\'Ivoire',
    CK: 'Cook Islands',
    CL: 'Chile',
    CM: 'Cameroon',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cape Verde',
    CW: 'Curacao',
    CX: 'Christmas Island',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DE: 'Germany',
    DJ: 'Djibouti',
    DK: 'Denmark',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    ER: 'Eritrea',
    ES: 'Spain',
    ET: 'Ethiopia',
    FI: 'Finland',
    FJ: 'Fiji',
    FM: 'Federated States of Micronesia',
    FR: 'France',
    GA: 'Gabon',
    GB: 'United Kingdom',
    GD: 'Grenada',
    GE: 'Georgia',
    GG: 'Guernsey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Greenland',
    GM: 'The Gambia',
    GN: 'Guinea',
    GQ: 'Equatorial Guinea',
    GR: 'Greece',
    GS: 'South Georgia and the South Sandwich Islands',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HK: 'Hong Kong',
    HM: 'Heard Island and McDonald Islands',
    HN: 'Honduras',
    HR: 'Croatia',
    HT: 'Haiti',
    HU: 'Hungary',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IM: 'Isle of Man,United Kingdom',
    IN: 'India',
    IQ: 'Iraq',
    IR: 'Iran',
    IS: 'Iceland',
    IT: 'Italy',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Kyrgyzstan',
    KH: 'Cambodia',
    KI: 'Kiribati',
    KM: 'Comoros',
    KN: 'Saint Kitts and Nevis',
    KP: 'North Korea',
    KR: 'South Korea',
    KW: 'Kuwait',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Lebanon',
    LC: 'Saint Lucia',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    LY: 'Libya',
    MA: 'Morocco',
    MC: 'Monaco',
    MD: 'Moldova',
    ME: 'Montenegro',
    MG: 'Madagascar',
    MH: 'Marshall Islands',
    MK: 'North Macedonia',
    ML: 'Mali',
    MM: 'Myanmar (Burma)',
    MN: 'Mongolia',
    MP: 'Northern Mariana Islands',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'New Caledonia',
    NE: 'Niger',
    NF: 'Norfolk Island',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NO: 'Norway',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PF: 'French Polynesia',
    PG: 'Papua New Guinea',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Poland',
    PM: 'Saint Pierre and Miquelon',
    PN: 'Pitcairn Islands',
    PR: 'Puerto Rico',
    PS: 'Palestine',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Qatar',
    RO: 'Romania',
    RS: 'Serbia',
    RU: 'Russia',
    RW: 'Rwanda',
    SA: 'Saudi Arabia',
    SB: 'Solomon Islands',
    SC: 'Seychelles',
    SD: 'Sudan',
    SE: 'Sweden',
    SG: 'Singapore',
    SH: 'Saint Helena, Ascension and Tristan da Cunha',
    SI: 'Slovenia',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Suriname',
    ST: 'Sao Tome and Principe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Syria',
    SZ: 'Eswatini',
    TD: 'Chad',
    TF: 'French Southern and Antarctic Lands',
    TG: 'Togo',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TO: 'Tonga',
    TR: 'Turkey',
    TT: 'Trinidad and Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwan',
    TZ: 'Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    UK: 'United Kingdom',
    UM: 'United States Minor Outlying Islands',
    US: 'United States',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VA: 'Vatican City',
    VC: 'Saint Vincent and the Grenadines',
    VE: 'Venezuela',
    VG: 'British Virgin Islands',
    VI: 'U.S. Virgin Islands',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis and Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    ZA: 'South Africa',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
};

// scraped from https://duckduckgo.com/params
E.duckduckgo_list = {
    'xa-ar': 'Arabia',
    'xa-en': 'Arabia (en)',
    'ar-es': 'Argentina',
    'au-en': 'Australia',
    'at-de': 'Austria',
    'be-fr': 'Belgium (fr)',
    'be-nl': 'Belgium (nl)',
    'br-pt': 'Brazil',
    'bg-bg': 'Bulgaria',
    'ca-en': 'Canada',
    'ca-fr': 'Canada (fr)',
    'ct-ca': 'Catalan',
    'cl-es': 'Chile',
    'cn-zh': 'China',
    'co-es': 'Colombia',
    'hr-hr': 'Croatia',
    'cz-cs': 'Czech Republic',
    'dk-da': 'Denmark',
    'ee-et': 'Estonia',
    'fi-fi': 'Finland',
    'fr-fr': 'France',
    'de-de': 'Germany',
    'gr-el': 'Greece',
    'hk-tzh': 'Hong Kong',
    'hu-hu': 'Hungary',
    'in-en': 'India',
    'id-id': 'Indonesia',
    'id-en': 'Indonesia (en)',
    'ie-en': 'Ireland',
    'il-he': 'Israel',
    'it-it': 'Italy',
    'jp-jp': 'Japan',
    'kr-kr': 'Korea',
    'lv-lv': 'Latvia',
    'lt-lt': 'Lithuania',
    'xl-es': 'Latin America',
    'my-ms': 'Malaysia',
    'my-en': 'Malaysia (en)',
    'mx-es': 'Mexico',
    'nl-nl': 'Netherlands',
    'nz-en': 'New Zealand',
    'no-no': 'Norway',
    'pe-es': 'Peru',
    'ph-en': 'Philippines',
    'ph-tl': 'Philippines (tl)',
    'pl-pl': 'Poland',
    'pt-pt': 'Portugal',
    'ro-ro': 'Romania',
    'ru-ru': 'Russia',
    'sg-en': 'Singapore',
    'sk-sk': 'Slovak Republic',
    'sl-sl': 'Slovenia',
    'za-en': 'South Africa',
    'es-es': 'Spain',
    'se-sv': 'Sweden',
    'ch-de': 'Switzerland (de)',
    'ch-fr': 'Switzerland (fr)',
    'ch-it': 'Switzerland (it)',
    'tw-tzh': 'Taiwan',
    'th-th': 'Thailand',
    'tr-tr': 'Turkey',
    'ua-uk': 'Ukraine',
    'uk-en': 'United Kingdom',
    'us-en': 'United States',
    'ue-es': 'United States (es)',
    've-es': 'Venezuela',
    'vn-vi': 'Vietnam',
    'wt-wt': 'No region'
};

// scraped from https://www.bing.com/account/general#region-section and
// https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-custom-search-api-v7-reference#market-codes
E.bing_list = {
    'prs-af': 'Afghanistan',
    'sq-al': 'Albania',
    'en-dz': 'Algeria',
    'en-as': 'American Samoa',
    'ca-ad': 'Andorra',
    'en-ao': 'Angola',
    'en-ai': 'Anguilla',
    'en-ag': 'Antigua and Barbuda',
    'es-ar': 'Argentina',
    'hy-am': 'Armenia',
    'nl-aw': 'Aruba',
    'en-au': 'Australia',
    'de-at': 'Austria',
    'en-az': 'Azerbaijan',
    'en-bs': 'Bahamas',
    'en-bh': 'Bahrain',
    'en-bd': 'Bangladesh',
    'en-bb': 'Barbados',
    'be-by': 'Belarus',
    'nl-be': 'Belgium - Dutch',
    'fr-be': 'Belgium - French',
    'en-bz': 'Belize',
    'en-bj': 'Benin',
    'en-bm': 'Bermuda',
    'bo-bt': 'Bhutan',
    'es-bo': 'Bolivia',
    'en-ba': 'Bosnia & Herzegovina',
    'en-bw': 'Botswana',
    'pt-br': 'Brazil',
    'en-vg': 'British Virgin Islands',
    'ms-bn': 'Brunei',
    'bg-bg': 'Bulgaria',
    'en-bf': 'Burkina Faso',
    'en-bi': 'Burundi',
    'en-cv': 'Cabo Verde',
    'km-kh': 'Cambodia',
    'en-cm': 'Cameroon',
    'en-ca': 'Canada - English',
    'fr-ca': 'Canada - French',
    'en-ky': 'Cayman Islands',
    'en-cf': 'Central African Republic',
    'en-td': 'Chad',
    'es-cl': 'Chile',
    'zh-cn': 'China',
    'en-cx': 'Christmas Island',
    'en-cc': 'Cocos (Keeling) Islands',
    'es-co': 'Colombia',
    'fr-km': 'Comoros',
    'fr-cg': 'Congo',
    'fr-cd': 'Congo (DRC)',
    'en-ck': 'Cook Islands',
    'es-cr': 'Costa Rica',
    'fr-ci': 'Côte d’Ivoire',
    'hr-hr': 'Croatia',
    'nl-cw': 'Curaçao',
    'en-cy': 'Cyprus',
    'cs-cz': 'Czechia',
    'da-dk': 'Denmark',
    'en-dj': 'Djibouti',
    'en-dm': 'Dominica',
    'es-do': 'Dominican Republic',
    'es-ec': 'Ecuador',
    'en-eg': 'Egypt',
    'es-sv': 'El Salvador',
    'en-gq': 'Equatorial Guinea',
    'en-er': 'Eritrea',
    'et-ee': 'Estonia',
    'en-sz': 'Eswatini',
    'am-et': 'Ethiopia',
    'en-fk': 'Falkland Islands',
    'fo-fo': 'Faroe Islands',
    'en-fj': 'Fiji',
    'fi-fi': 'Finland',
    'fr-fr': 'France',
    'fr-gf': 'French Guiana',
    'fr-pf': 'French Polynesia',
    'fr-ga': 'Gabon',
    'en-gm': 'Gambia',
    'ka-ge': 'Georgia',
    'de-de': 'Germany',
    'en-gh': 'Ghana',
    'en-gi': 'Gibraltar',
    'en-gr': 'Greece',
    'kl-gl': 'Greenland',
    'en-gd': 'Grenada',
    'fr-gp': 'Guadeloupe',
    'en-gu': 'Guam',
    'es-gt': 'Guatemala',
    'en-gg': 'Guernsey',
    'en-gn': 'Guinea',
    'en-gw': 'Guinea-Bissau',
    'en-gy': 'Guyana',
    'fr-ht': 'Haiti',
    'es-hn': 'Honduras',
    'zh-hk': 'Hong Kong SAR',
    'en-hu': 'Hungary',
    'is-is': 'Iceland',
    'en-in': 'India',
    'en-id': 'Indonesia',
    'fa-ir': 'Iran',
    'en-iq': 'Iraq',
    'en-ie': 'Ireland',
    'en-il': 'Israel',
    'it-it': 'Italy',
    'en-jm': 'Jamaica',
    'ja-jp': 'Japan',
    'en-je': 'Jersey',
    'en-jo': 'Jordan',
    'kk-kz': 'Kazakhstan',
    'sw-ke': 'Kenya',
    'en-ki': 'Kiribati',
    'ko-kr': 'Korea',
    'en-kw': 'Kuwait',
    'ky-kg': 'Kyrgyzstan',
    'en-la': 'Laos',
    'lv-lv': 'Latvia',
    'en-lb': 'Lebanon',
    'en-ls': 'Lesotho',
    'en-lr': 'Liberia',
    'en-ly': 'Libya',
    'de-li': 'Liechtenstein',
    'lt-lt': 'Lithuania',
    'fr-lu': 'Luxembourg',
    'en-mo': 'Macao SAR',
    'fr-mg': 'Madagascar',
    'en-mw': 'Malawi',
    'en-my': 'Malaysia',
    'en-mv': 'Maldives',
    'en-ml': 'Mali',
    'mt-mt': 'Malta',
    'en-mh': 'Marshall Islands',
    'fr-mq': 'Martinique',
    'en-mr': 'Mauritania',
    'en-mu': 'Mauritius',
    'fr-yt': 'Mayotte',
    'es-mx': 'Mexico',
    'en-fm': 'Micronesia',
    'en-md': 'Moldova',
    'fr-mc': 'Monaco',
    'mn-mn': 'Mongolia',
    'en-me': 'Montenegro',
    'en-ms': 'Montserrat',
    'en-ma': 'Morocco',
    'en-mz': 'Mozambique',
    'en-mm': 'Myanmar',
    'en-na': 'Namibia',
    'en-nr': 'Nauru',
    'ne-np': 'Nepal',
    'nl-nl': 'Netherlands',
    'fr-nc': 'New Caledonia',
    'en-nz': 'New Zealand',
    'es-ni': 'Nicaragua',
    'en-ne': 'Niger',
    'en-ng': 'Nigeria',
    'en-nu': 'Niue',
    'en-nf': 'Norfolk Island',
    'mk-mk': 'North Macedonia',
    'en-mp': 'Northern Mariana Islands',
    'nb-no': 'Norway',
    'en-om': 'Oman',
    'en-pk': 'Pakistan',
    'en-pw': 'Palau',
    'en-ps': 'Palestinian Authority',
    'es-pa': 'Panama',
    'en-pg': 'Papua New Guinea',
    'es-py': 'Paraguay',
    'es-pe': 'Peru',
    'en-ph': 'Philippines',
    'en-pn': 'Pitcairn Islands',
    'pl-pl': 'Poland',
    'pt-pt': 'Portugal',
    'es-pr': 'Puerto Rico',
    'en-qa': 'Qatar',
    'en-re': 'Réunion',
    'ro-ro': 'Romania',
    'ru-ru': 'Russia',
    'rw-rw': 'Rwanda',
    'fr-bl': 'Saint Barthélemy',
    'en-kn': 'Saint Kitts and Nevis',
    'en-lc': 'Saint Lucia',
    'fr-mf': 'Saint Martin',
    'fr-pm': 'Saint Pierre and Miquelon',
    'en-vc': 'Saint Vincent and the Grenadines',
    'en-ws': 'Samoa',
    'en-sm': 'San Marino',
    'en-st': 'São Tomé & Príncipe',
    'en-sa': 'Saudi Arabia',
    'fr-sn': 'Senegal',
    'en-rs': 'Serbia',
    'en-sc': 'Seychelles',
    'en-sl': 'Sierra Leone',
    'en-sg': 'Singapore',
    'nl-sx': 'Sint Maarten',
    'en-sk': 'Slovakia',
    'sl-si': 'Slovenia',
    'en-sb': 'Solomon Islands',
    'en-so': 'Somalia',
    'en-za': 'South Africa',
    'en-ss': 'South Sudan',
    'es-es': 'Spain',
    'si-lk': 'Sri Lanka',
    'en-sh': 'St Helena, Ascension, Tristan da Cunha',
    'en-sd': 'Sudan',
    'en-sr': 'Suriname',
    'sv-se': 'Sweden',
    'fr-ch': 'Switzerland - French',
    'de-ch': 'Switzerland - German',
    'en-sy': 'Syria',
    'zh-tw': 'Taiwan',
    'en-tj': 'Tajikistan',
    'en-tz': 'Tanzania',
    'th-th': 'Thailand',
    'pt-tl': 'Timor-Leste',
    'fr-tg': 'Togo',
    'en-tk': 'Tokelau',
    'en-to': 'Tonga',
    'en-tt': 'Trinidad and Tobago',
    'en-tn': 'Tunisia',
    'tr-tr': 'Turkey',
    'tk-tm': 'Turkmenistan',
    'en-tc': 'Turks and Caicos Islands',
    'en-tv': 'Tuvalu',
    'en-vi': 'U.S. Virgin Islands',
    'en-ug': 'Uganda',
    'uk-ua': 'Ukraine',
    'en-ae': 'United Arab Emirates',
    'en-gb': 'United Kingdom',
    'en-us': 'United States - English',
    'es-us': 'United States - Spanish',
    'es-uy': 'Uruguay',
    'en-uz': 'Uzbekistan',
    'en-vu': 'Vanuatu',
    'it-va': 'Vatican City',
    'es-ve': 'Venezuela',
    'en-vn': 'Vietnam',
    'fr-wf': 'Wallis and Futuna',
    'en-ye': 'Yemen',
    'en-zm': 'Zambia',
    'en-zw': 'Zimbabwe',
};

E.currency = {
    AD: 'EUR', AE: 'AED', AF: 'AFN', AG: 'XCD', AI: 'XCD', AL: 'ALL',
    AM: 'AMD', AN: 'ANG', AO: 'AOA', AR: 'ARS', AS: 'USD', AT: 'EUR',
    AU: 'AUD', AW: 'AWG', AX: 'EUR', AZ: 'AZN', BA: 'BAM', BB: 'BBD',
    BD: 'BDT', BE: 'EUR', BF: 'XOF', BG: 'BGN', BH: 'BHD', BI: 'BIF',
    BJ: 'XOF', BL: 'EUR', BM: 'BMD', BN: 'BND', BO: 'BOB', BQ: 'USD',
    BR: 'BRL', BS: 'BSD', BT: 'BTN', BW: 'BWP', BY: 'BYN', BZ: 'BZD',
    CA: 'CAD', CC: 'AUD', CD: 'CDF', CF: 'XAF', CG: 'XAF', CH: 'CHF',
    CI: 'XOF', CK: 'NZD', CL: 'CLP', CM: 'XAF', CN: 'CNY', CO: 'COP',
    CR: 'CRC', CU: 'CUP', CV: 'CVE', CW: 'ANG', CX: 'AUD', CY: 'EUR',
    CZ: 'CZK', DE: 'EUR', DJ: 'DJF', DK: 'DKK', DM: 'XCD', DO: 'DOP',
    DZ: 'DZD', EC: 'USD', EE: 'EUR', EG: 'EGP', EH: 'MAD', ER: 'ERN',
    ES: 'EUR', ET: 'ETB', EU: 'EUR', FI: 'EUR', FJ: 'FJD', FK: 'FKP',
    FM: 'USD', FO: 'DKK', FR: 'EUR', GA: 'XAF', GB: 'GBP', GD: 'XCD',
    GE: 'GEL', GF: 'EUR', GG: 'GBP', GH: 'GHS', GI: 'GIP', GL: 'DKK',
    GM: 'GMD', GN: 'GNF', GP: 'EUR', GQ: 'XAF', GR: 'EUR', GS: 'FKP',
    GT: 'GTQ', GU: 'USD', GW: 'XOF', GY: 'GYD', HK: 'HKD', HN: 'HNL',
    HR: 'HRK', HT: 'HTG', HU: 'HUF', ID: 'IDR', IE: 'EUR', IL: 'ILS',
    IM: 'GBP', IN: 'INR', IO: 'USD', IQ: 'IQD', IR: 'IRR', IS: 'ISK',
    IT: 'EUR', JE: 'GBP', JM: 'JMD', JO: 'JOD', JP: 'JPY', KE: 'KES',
    KG: 'KGS', KH: 'KHR', KI: 'AUD', KM: 'KMF', KN: 'XCD', KP: 'KPW',
    KR: 'KRW', KW: 'KWD', KY: 'KYD', KZ: 'KZT', LA: 'LAK', LB: 'LBP',
    LC: 'XCD', LI: 'CHF', LK: 'LKR', LR: 'LRD', LS: 'LSL', LT: 'EUR',
    LU: 'EUR', LV: 'EUR', LY: 'LYD', MA: 'MAD', MC: 'EUR', MD: 'MDL',
    ME: 'EUR', MF: 'EUR', MG: 'MGA', MH: 'USD', MK: 'MKD', ML: 'XOF',
    MM: 'MMK', MN: 'MNT', MO: 'MOP', MP: 'USD', MQ: 'EUR', MR: 'MRU',
    MS: 'XCD', MT: 'EUR', MU: 'MUR', MV: 'MVR', MW: 'MWK', MX: 'MXN',
    MY: 'MYR', MZ: 'MZN', NA: 'NAD', NC: 'XPF', NE: 'XOF', NF: 'AUD',
    NG: 'NGN', NI: 'NIO', NL: 'EUR', NO: 'NOK', NP: 'NPR', NR: 'AUD',
    NU: 'NZD', NZ: 'NZD', OM: 'OMR', PA: 'PAB', PE: 'PEN', PF: 'XPF',
    PG: 'PGK', PH: 'PHP', PK: 'PKR', PL: 'PLN', PM: 'EUR', PN: 'NZD',
    PR: 'USD', PS: 'ILS', PT: 'EUR', PW: 'USD', PY: 'PYG', QA: 'QAR',
    RE: 'EUR', RO: 'RON', RS: 'RSD', RU: 'RUB', RW: 'RWF', SA: 'SAR',
    SB: 'SBD', SC: 'SCR', SD: 'SDG', SE: 'SEK', SG: 'SGD', SH: 'SHP',
    SI: 'EUR', SJ: 'NOK', SK: 'EUR', SL: 'SLL', SM: 'EUR', SN: 'XOF',
    SO: 'SOS', SR: 'SRD', SS: 'SSP', ST: 'STN', SV: 'USD', SX: 'ANG',
    SY: 'SYP', SZ: 'SZL', TC: 'USD', TD: 'XAF', TF: 'EUR', TG: 'XOF',
    TH: 'THB', TJ: 'TJS', TK: 'NZD', TL: 'USD', TM: 'TMT', TN: 'TND',
    TO: 'TOP', TR: 'TRY', TT: 'TTD', TV: 'AUD', TW: 'TWD', TZ: 'TZS',
    UA: 'UAH', UG: 'UGX', UK: 'GBP', UM: 'USD', US: 'USD', UY: 'UYU',
    UZ: 'UZS', VA: 'EUR', VC: 'XCD', VE: 'VES', VG: 'GBP', VI: 'USD',
    VN: 'VND', VU: 'VUV', WF: 'XPF', WS: 'WST', XK: 'EUR', YE: 'YER',
    YT: 'EUR', ZA: 'ZAR', ZM: 'ZMW', ZW: 'USD',
};

var gs1_countries_list = {
    AL: '530',
    DZ: '613',
    AR: '778-779',
    AM: '485',
    AU: '930-939',
    AT: '900-919',
    AZ: '476',
    BH: '608',
    BY: '481',
    BO: '777',
    BA: '387',
    BR: '789-790',
    BN: '623',
    BG: '380',
    KH: '884',
    CA: '754-755',
    CL: '780',
    CN: '690-699',
    CO: '770-771',
    CR: '744',
    HR: '385',
    CU: '850',
    CY: '529',
    CZ: '859',
    DK: '570-579',
    DO: '746',
    EC: '786',
    EG: '622',
    SV: '741',
    EE: '474',
    FI: '640-649',
    GE: '486',
    DE: '400-440',
    GH: '603',
    GR: '520-521',
    GL: '570-579',
    GT: '740',
    HN: '742',
    HK: '489',
    HU: '599',
    IS: '569',
    IN: '890',
    ID: '899',
    IR: '626',
    IL: '729',
    CI: '618',
    JP: '450-459',
    JO: '625',
    KE: '616',
    KW: '627',
    KG: '470',
    LV: '475',
    LB: '528',
    LT: '477',
    MK: '531',
    MY: '955',
    MT: '535',
    MU: '609',
    MX: '750',
    MD: '484',
    MN: '865',
    MA: '611',
    NL: '870-879',
    NZ: '940-949',
    NI: '743',
    NG: '615',
    KP: '867',
    NO: '700-709',
    PK: '896',
    PA: '745',
    PY: '784',
    PE: '775',
    PH: '480',
    PL: '590',
    PT: '560',
    RO: '594',
    SA: '628',
    SN: '604',
    RS: '860',
    SG: '888',
    SK: '858',
    SI: '383',
    ZA: '600-601',
    KR: '880',
    SY: '621',
    TJ: '488',
    TZ: '620',
    TH: '885',
    TN: '619',
    TR: '868-869',
    TM: '483',
    UA: '482',
    AE: '629',
    UK: '500-509',
    US: '000-139',
    UY: '773',
    UZ: '478',
    VE: '759',
    VN: '893'
};

E.us_states = {
    AK: 'Alaska',
    AL: 'Alabama',
    AR: 'Arkansas',
    AZ: 'Arizona',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DC: 'District of Columbia',
    DE: 'Delaware',
    FL: 'Florida',
    GA: 'Georgia',
    HI: 'Hawaii',
    IA: 'Iowa',
    ID: 'Idaho',
    IL: 'Illinois',
    IN: 'Indiana',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    MA: 'Massachusetts',
    MD: 'Maryland',
    ME: 'Maine',
    MI: 'Michigan',
    MN: 'Minnesota',
    MO: 'Missouri',
    MS: 'Mississippi',
    MT: 'Montana',
    NC: 'North Carolina',
    ND: 'North Dakota',
    NE: 'Nebraska',
    NH: 'New Hampshire',
    NJ: 'New Jersey',
    NM: 'New Mexico',
    NV: 'Nevada',
    NY: 'New York',
    OH: 'Ohio',
    OK: 'Oklahoma',
    OR: 'Oregon',
    PA: 'Pennsylvania',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VA: 'Virginia',
    VT: 'Vermont',
    WA: 'Washington',
    WI: 'Wisconsin',
    WV: 'West Virginia',
    WY: 'Wyoming',
};
E.us_states_timezone = {
    AK: 'America/Anchorage',
    AL: 'America/Chicago',
    AR: 'America/Chicago',
    AZ: 'America/Phoenix',
    CA: 'America/Los_Angeles',
    CO: 'America/Denver',
    CT: 'America/New_York',
    DC: 'America/New_York',
    DE: 'America/New_York',
    FL: 'America/New_York',
    GA: 'America/New_York',
    HI: 'Pacific/Honolulu',
    IA: 'America/Chicago',
    ID: 'America/Denver',
    IL: 'America/Chicago',
    IN: 'America/New_York',
    KS: 'America/Chicago',
    KY: 'America/Chicago',
    LA: 'America/Chicago',
    MA: 'America/New_York',
    MD: 'America/New_York',
    ME: 'America/New_York',
    MI: 'America/Detroit',
    MN: 'America/Chicago',
    MO: 'America/Chicago',
    MS: 'America/Chicago',
    MT: 'America/Denver',
    NC: 'America/New_York',
    ND: 'America/Chicago',
    NE: 'America/Chicago',
    NH: 'America/New_York',
    NJ: 'America/New_York',
    NM: 'America/Denver',
    NV: 'America/Los_Angeles',
    NY: 'America/New_York',
    OH: 'America/New_York',
    OK: 'America/Chicago',
    OR: 'America/Los_Angeles',
    PA: 'America/New_York',
    RI: 'America/New_York',
    SC: 'America/New_York',
    SD: 'America/Chicago',
    TN: 'America/Chicago',
    TX: 'America/Chicago',
    UT: 'America/Denver',
    VA: 'America/New_York',
    VT: 'America/New_York',
    WA: 'America/Los_Angeles',
    WI: 'America/Chicago',
    WV: 'America/New_York',
    WY: 'America/Denver',
};
E.us_states2code = {};
for (var s in E.us_states)
    E.us_states2code[E.us_states[s]] = s;

E.code2label = function(c){
    c = c.toUpperCase();
    return E.list[c] || c;
};

E.code2adj = function(c){
    c = c.toUpperCase();
    return E.adj_list[c] || c;
};

E.code2timezone = function(c){
    c = c.toUpperCase();
    return E.timezone[c] || c;
};

E.state_code2timezone = function(ts_country, state){
    if (ts_country!='US')
        return;
    state = state.toUpperCase();
    return E.us_states_timezone[state];
};

E.label2code = function(label){
    var c_list = Object.entries(E.list).concat(Object.entries(E.google_list));
    for (var i = 0; i<c_list.length; i++)
    {
        var _c = c_list[i];
        if (_c[1]===label)
            return _c[0];
        var bracket_ind = _c[1].indexOf('(');
        if (bracket_ind!=-1 && _c[1].slice(0, bracket_ind-1)==label)
            return _c[0];
    }
    // XXX sergeim: Åland Islands case
    for (var k in E.adj_list)
    {
        if (E.adj_list[k].name==label)
            return k;
    }
    var exc = {
        'Macedonia (FYROM)': 'MK',
    };
    return exc[label] || '';
};

E.cnlabel2code = function(label){
    for (var i in E.cn_list)
    {
        if (E.cn_list[i]===label)
            return i;
    }
    return '';
};

E.alpha3_to_alpha2 = function alpha3_to_alpha2(a3){
    a3 = a3.toUpperCase();
    var alpha2 = Object.keys(alpha_3_list);
    var alpha3 = Object.values(alpha_3_list);
    var a2 = alpha2[alpha3.indexOf(a3)];
    return a2||a3;
};

E.mixed2code = function(mixed){
    if (!mixed)
        return;
    if (/^[A-Z]{2}$/.test(mixed))
        return mixed;
    if (mixed.length==2)
        return mixed.toUpperCase();
    for (var ccode in E.list)
    {
        if (E.list[ccode].toLowerCase()==mixed.toLowerCase())
            return ccode;
    }
    if (mixed.length==3)
    {
        for (var acode in alpha_3_list)
        {
            if (alpha_3_list[acode].toLowerCase()==mixed.toLowerCase())
                return acode;
        }
    }
    return mixed;
};

E.www2code = function(c){
    return c=='UK' ? 'GB' : c=='uk' ? 'gb' : c; };

E.code2www = function(c){
    return c=='GB' ? 'UK' : c=='gb' ? 'uk' : c; };

E.gl2uule = function(gl){
    gl = E.www2code(gl.toUpperCase());
    // Google doesn't recognize uule="North Macedonia". This name is kept in
    // E.google_list though to be equal to official label in Google settings
    // (https://www.google.com/preferences).
    if (gl=='MK')
        return 'Macedonia';
    return E.google_list[gl] || gl;
};

var uule_to_gl_map = {};
for (var gl_code in E.google_list)
{
    gl_code = E.www2code(gl_code);
    var uule_country = E.google_list[gl_code].toLowerCase();
    uule_to_gl_map[uule_country] = gl_code;
}
E.uule2gl = function(uule){
    uule = uule.toLowerCase();
    if (uule=='macedonia')
        return 'MK';
    return E.www2code(uule_to_gl_map[uule]);
};

var gs1_countries_rlist = {};
Object.entries(gs1_countries_list).forEach(function(entry){
    var value = entry[1];
    if (value.includes('-'))
    {
        var ranges = value.split('-');
        for (var i = +ranges[0]; i <= +ranges[1]; i++)
            gs1_countries_rlist[i.toString().padStart(3, '0')] = entry[0];
    }
    else
        gs1_countries_rlist[value.toString().padStart(3, '0')] = entry[0];
});
E.gtin_to_country = function(gtin){
    if (gtin.length > 14 || gtin.length < 13)
        return;
    if (gtin.length == 14 && gtin.charAt(0) == '0')
        gtin = gtin.substring(1);
    return gs1_countries_rlist[gtin.slice(0, 3)];
};

return E; }); }());
